### ISSUE TITLE
Invalid `photon.()` invocation

### ISSUE THREAD

**Issue by Andrew1325** [prisma/prisma-client-js#373]
I have received this issue today. I haven't made any changes to my prisma setup at all in the last few days and have only received this error just now. 

```
Error: 
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `photon.()` invocation in /Users/redqueen/courses/sapper/prisma2api/rising-api/src/types/Query.ts:69:33

Reason: called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None } in src/libcore/result.rs:1165:5

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use 🙏:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (/Users/redqueen/courses/sapper/prisma2api/rising-api/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/redqueen/courses/sapper/prisma2api/rising-api/node_modules/@prisma/photon/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Invalid `photon.()` invocation in /Users/redqueen/courses/sapper/prisma2api/rising-api/src/types/Query.ts:22:33

undefined target="exit" timestamp="2020-01-02T09:18:52.360Z" fields={"message":"255"}
    at PhotonFetcher.<anonymous> (/Users/redqueen/courses/sapper/prisma2api/rising-api/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/redqueen/courses/sapper/prisma2api/rising-api/node_modules/@prisma/photon/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Invalid `photon.()` invocation in /Users/redqueen/courses/sapper/prisma2api/rising-api/src/types/Query.ts:69:33
... plus a bit more ...
```

my schema.prisma:

```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = "### my heroku postgres url ###"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  password String
  name  String?
  posts Post[]
  bids Bid[]
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}

model Item {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  description   String?
  openingDate String
  closingDate String
  bids Bid[]
}

model Bid {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  amount Float
  bidder User
  item Item
}
```

The method being called was a simple query:

```
t.list.field('items', {
      type: 'Item',
      resolve: (parent, args, ctx) => {
        return ctx.photon.items.findMany({})
      },
    })
```

As I said, was working perfectly until just now.

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/photonjs/issues/357

**Comment by divyenduz** [comment]
@Andrew1325 Once the related issue is fixed, you will see a better error message. Currently, Photon is eating up some of the errors and the error message is incomplete. 

Just to be sure, can you confirm if you have all the environment variables etc in place? That was the most common error being eaten up by Photon.

**Comment by divyenduz** [comment]
@Andrew1325 Since #357 is fixed, can you please try this again and see what the actual error is? Thanks.

**Comment by janpio** [comment]
Ping @Andrew1325

**Comment by timsuchanek** [comment]
This issue has already been fixed a while ago. If you still face it, let us know and we reopen it.
