### ISSUE TITLE
Unknown error in create()

### ISSUE THREAD

**Issue by JWambaugh** [prisma/prisma-client-js#417]
I'm getting an unknown error when running `create()`.

mysql
linux
2.0.0-preview019

Function Call:
```
photon.annotations.create({
  data: {
    text: 'Hello world',
    author: { connect:{ id: 0 } },
    verse: { connect: {id: 1} }
  }
});
```

Schema:
```
model User {
  id          Int          @id @default(autoincrement())
  name        String       @unique
  email       String       @unique
  password    String
  authTokens  AuthToken[]
  annotations Annotation[]
  role        Role
}

model Role {
  id          Int          @id @default(autoincrement())
  name        String
  permissions Permission[]
}

model Permission {
  id    Int    @id @default(autoincrement())
  name  String
  roles Role[]
}

model AuthToken {
  id        Int      @id @default(autoincrement())
  token     String
  createdAt DateTime @default(now())
  user      User
}

model Annotation {
  id        Int      @id @default(autoincrement())
  text      String
  verse     verse?
  chapter   chapter?
  author    User
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model verse {
  chapter        chapter?     @map(name: "chapter_id") @relation(name: "chapter_id")
  id             Int          @id
  scripture_text String
  verse_number   Int          @default(0)
  annotations    Annotation[]
}
```

Debug output:
```
photon Request: +0ms
  photon mutation {
  photon   createOneAnnotation(data: {
  photon     text: "Hello world"
  photon     author: {
  photon       connect: {
  photon         id: 0
  photon       }
  photon     }
  photon     verse: {
  photon       connect: {
  photon         id: 1
  photon       }
  photon     }
  photon   }) {
  photon     id
  photon     text
  photon     createdAt
  photon     updatedAt
  photon   }
  photon } +0ms
  engine {
  engine   error: CancelError: Promise was canceled
  engine       at PCancelable.cancel (/opt/korihor/server/node_modules/@prisma/photon/runtime/index.js:24533:17)
  engine       at NodeEngine.handlePanic (/opt/korihor/server/node_modules/@prisma/photon/runtime/index.js:3306:40)
  engine       at EventEmitter.<anonymous> (/opt/korihor/server/node_modules/@prisma/photon/runtime/index.js:3262:26)
  engine       at EventEmitter.emit (events.js:223:5)
  engine       at LineStream.<anonymous> (/opt/korihor/server/node_modules/@prisma/photon/runtime/index.js:3431:41)
  engine       at LineStream.emit (events.js:223:5)
  engine       at addChunk (_stream_readable.js:309:12)
  engine       at readableAddChunk (_stream_readable.js:290:11)
  engine       at LineStream.Readable.push (_stream_readable.js:224:10)
  engine       at LineStream.Transform.push (_stream_transform.js:150:32) {
  engine     name: 'CancelError'
  engine   }
  engine } +6s
Error:
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `photon.()` invocation in /opt/korihor/server/src/resolvers/index.js:57:41



Reason: called `Option::unwrap()` on a `None` value in src/libcore/option.rs:378:21

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use �🚀:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (/opt/korihor/server/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/opt/korihor/server/node_modules/@prisma/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by pantharshit00** [comment]
Can you please paste your complete datamodel?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/22195362/72920984-64809000-3d70-11ea-8ae6-17e84c96dc63.png">


Looks like you missed out the `chapter` model.

**Comment by JWambaugh** [comment]
Thanks @pantharshit00. This is fixed now in preview20. I'll go ahead and close.
