### ISSUE TITLE
Photon crashes when `set` for scalarList is not provided or it is set to `[]`

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [prisma/prisma-client-js#422]
Hello im having this issue, i use prisma2@alpha and this is the repo https://github.com/GolfredoPerezFernandez/PrismaServer .

```
Error:Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `return await ctx.photon.posts.create()` invocation in C:\Users\owner\Documents\modern-apps\lightmatter\new\src\types\Mutation.ts:353:43

  349
  350 console.log(evarepsilon1Y.length)
  351
  352 console.log(malla.length)
→ 353   return await ctx.photon.posts.create({

Reason: called `Option::unwrap()` on a `None` value in src\libcore\option.rs:378:21

Please create an issue in the photonjs repo with
your `schema.prisma` and the Photon method you tried to use �:
https://github.com/prisma/photonjs/issues/new

    at PhotonFetcher.<anonymous> (C:\Users\owner\Documents\modern-apps\lightmatter\new\node_modules\@prisma\photon\index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\owner\Documents\modern-apps\lightmatter\new\node_modules\@prisma\photon\index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by pantharshit00** [comment]
@lvauvillier You message came as I was posting the above messages. I will try out your reproduction as well. If it also happens for enum, it is possible that bug is related to the new scalar list implementation.

**Comment by pantharshit00** [comment]
Yes, so I check your reproduction as well and it is also almost the exact case where set is omitted. So right now photon crashed if `set` is not provided for scalarList or it is set to `[]`. I think we should fix this behaviour.
