### ISSUE TITLE
Prisma Client crashes when querying field of type `TIMESTAMP WITH TIME ZONE` in PostgreSQL

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-client-js#427]
I started with this SQL schema on a PostgreSQL DB hosted on Heroku:

```sql
CREATE TABLE users (
	user_id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(256),
	email VARCHAR(256) UNIQUE NOT NULL
);
CREATE TABLE posts (
	post_id SERIAL PRIMARY KEY NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(256) NOT NULL,
	content TEXT,
	author_id INTEGER REFERENCES users(user_id) 
);
```

Then ran `prisma2 introspect` against it and got this Prisma schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "..."
}

model posts {
  author_id  users?
  content    String?
  created_at DateTime?
  post_id    Int       @id
  title      String
}

model users {
  email      String     @unique
  name       String?
  user_id    Int        @id
  postses    posts[]
}
```

Then I was using this Prisma Client API call to read all `users` with their `postses`:

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {

  const users = await prisma.users.findMany({
    include: {
      postses: true,
    }
  })
  console.log(JSON.stringify(users))
}

main()
```

When running the script, my code failed with this error:

```
$ npx ts-node script.ts
(node:51831) UnhandledPromiseRejectionWarning: Error: 
Invalid `const users = await prisma.users.findMany()` invocation in
/Users/nikolasburk/Desktop/prisma2-gse/script.ts:7:36

   3 const prisma = new PrismaClient()
   4 
   5 async function main() {
   6 
→  7   const users = await prisma.users.findMany(

Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(1), cause: Some(WrongType { postgres: Type(Timestamptz), rust: "core::option::Option<alloc::string::String>" }) }) })

    at PrismaClientFetcher.request (/Users/nikolasburk/Desktop/prisma2-gse/node_modules/@prisma/client/index.js:62:23)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:51831) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:51831) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment]
I am able to reproduce this:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/22195362/72922172-9561c480-3d72-11ea-9a84-9cc8968570a4.png">

In order to reproduce, you do need to have some data in your database.

**Comment by tomhoule** [comment]
I can confirm that this no longer happens, as of alpha 904. Next preview release will contain the fix.

**Comment by tomhoule** [comment]
I can confirm this is fixed in alpha 904. It will be in the next preview.
