### ISSUE TITLE
Unable to connect to PrismaClient

### ISSUE THREAD

**Issue by julien1619** [prisma/prisma-client-js#443]
When trying to connect to PrismaClient, it crashes with the following error:
```
Using ts-node version 8.6.2, typescript version 3.7.5
PrismaClientError: Reason: Invalid Host provided: AddrParseError(()) in src/libcore/result.rs:1165:5

Please create an issue in the prisma-client-js repo with
your `schema.prisma` and the Prisma Client method you tried to use 🙏:
https://github.com/prisma/prisma-client-js/issues/new

    at NodeEngine.engineReady (/Users/jblatecky/dev/arcadie/backend/node_modules/@prisma/client/runtime/index.js:3311:23)
    at /Users/jblatecky/dev/arcadie/backend/node_modules/@prisma/client/runtime/index.js:3230:21
```

The same schema was working with preview19.

I'm using the following versions:
```
"@prisma/client": "2.0.0-preview020.3"
"@prisma/sdk": "0.0.172"
"prisma2": "2.0.0-preview020.3"
```

Here is my schema:
```
generator prisma_client {
  provider = "prisma-client-js"
}

datasource postgres {
  url      = env("DATABASE_URL")
  provider = "postgres"
}

enum Language {
  EN
  FR
}

model User {
  id           String           @default(uuid()) @id
  email        String           @unique
  firstName    String?
  lastName     String?
  language     Language         @default(FR)
  createdAt    DateTime         @default(now())
  updatedAt    DateTime         @updatedAt
  devices      UserDevice[]
  permissions  UserPermission[]
  authPassword AuthPassword?
  authFailure  AuthFailure?
}

enum AuthenticatedRoute {
  CLIENT
  ADMIN
}

model UserPermission {
  id        String             @default(uuid()) @id
  user      User               @relation(references: [id])
  route     AuthenticatedRoute
  createdAt DateTime           @default(now())
}

enum Platform {
  WEB
  IOS
  ANDROID
}

model UserDevice {
  id                 String             @default(uuid()) @id
  user               User               @relation(references: [id])
  deviceId           String
  route              AuthenticatedRoute
  platform           Platform
  notificationToken  String?
  hashedRefreshToken String
  description        String
  lastUsageAt        DateTime           @default(now())
  createdAt          DateTime           @default(now())
  updatedAt          DateTime           @updatedAt
}

model AuthPassword {
  id             String   @default(uuid()) @id
  user           User     @relation(references: [id])
  hashedPassword String
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
}

model AuthFailure {
  id        String   @default(uuid()) @id
  user      User     @relation(references: [id])
  count     Int      @default(0)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this. I was successfully able to deploy this schema and able to query data from it. 

The error suggests that you have a problem in your connection url for your database. Since you have used an environment variable, I cannot verify what connection string you are using. Can you please make sure that you are using a valid connection string.

If the problem still exists, maybe share your connection string with proper masking of username and password in it

**Comment by julien1619** [comment]
I tried with preview21 and it works now. Thank you.
