### ISSUE TITLE
Postinstall: `undefined` and Error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#467]
```
C:\Users\Jan\Documents\throwaway\1496
λ npm install @prisma/client@alpha

> @prisma/client@2.0.0-alpha.735 postinstall C:\Users\Jan\Documents\throwaway\1496\node_modules\@prisma\client
> node scripts/postinstall.js

undefined
Error: In order to use "@prisma/client", please install prisma2. You can install it with "npm add -D prisma2".
    at main (C:\Users\Jan\Documents\throwaway\1496\node_modules\@prisma\client\scripts\postinstall.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\1496\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\1496\package.json'
npm WARN @prisma/client@2.0.0-alpha.735 requires a peer of prisma2@* but none is installed. You must install peer dependencies yourself.
npm WARN 1496 No description
npm WARN 1496 No repository field.
npm WARN 1496 No README data
npm WARN 1496 No license field.

+ @prisma/client@2.0.0-alpha.735
updated 1 package and audited 1 package in 4.991s
found 0 vulnerabilities
```

1. This `undefined` should probably not be there?
2. Why is `In order to use "@prisma/client", please install prisma2. You can install it with "npm add -D prisma2"` an error? Isn't this more like a warning? (similar to `npm WARN` further down)

**Comment by timsuchanek** [comment]
1. Yes the `undefined` shouldn't be there
2. True, we can turn that into a warning.
