### ISSUE TITLE
Cannot read property 'plural' of undefined     at PrismaClientClass.get jsDoc

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-client-js#472]
Reproduction
- `prisma2 init`
- `npm install @prisma/client@alpha`

```console
npm install @prisma/client@alpha

> @prisma/client@2.0.0-alpha.751 postinstall /Users/j42/Dev/prisma2-1367/node_modules/@prisma/client
> node scripts/postinstall.js

GeneratorError: TypeError: Cannot read property 'plural' of undefined
    at PrismaClientClass.get jsDoc [as jsDoc] (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:663219)
    at PrismaClientClass.toTS (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:665013)
    at TSClient.toTS (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:655650)
    at Object.TS (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:647022)
    at buildClient (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:881622)
    at Object.generateClient (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:882220)
    at Object.onGenerate (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:958927)
    at Object.<anonymous> (/Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:504622)
    at Generator.next (<anonymous>)
    at /Users/j42/Dev/prisma2-1367/node_modules/@prisma/client/generator-build/index.js:2:504272
    at GeneratorProcess.handleResponse (/Users/j42/.fnm/node-versions/v12.14.1/installation/lib/node_modules/prisma2/build/index.js:110539:35)
    at LineStream.<anonymous> (/Users/j42/.fnm/node-versions/v12.14.1/installation/lib/node_modules/prisma2/build/index.js:110517:26)
    at LineStream.emit (events.js:223:5)
    at LineStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream.module.exports.2514.LineStream._pushBuffer (/Users/j42/.fnm/node-versions/v12.14.1/installation/lib/node_modules/prisma2/build/index.js:41265:23)
    at LineStream.module.exports.2514.LineStream._transform (/Users/j42/.fnm/node-versions/v12.14.1/installation/lib/node_modules/prisma2/build/index.js:41257:10) {
  code: -32000,
  data: null
}

```

**Comment by timsuchanek** [comment]
It turned out, that this is fixed in the latest alpha.
