### ISSUE TITLE
`EROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#476]
I "followed" the setup in https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/netlify and used the `netlify` command to deploy to upload a locally created `.zip`. 

When then calling the function, I get:

```
{"errorType":"Error","errorMessage":"\nInvalid `prisma.()` invocation in\n/var/task/generated/prisma-client/index.js:323:37\n\n\n\nEROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'","trace":["Error: ","Invalid `prisma.()` invocation in","/var/task/generated/prisma-client/index.js:323:37","","","","EROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'","    at PrismaClientFetcher.request (/var/task/generated/prisma-client/index.js:60:27)"]}
```

Theory: Because the the generated client was created on Windows, it is missing the necessary file permission flags.

**Comment by simonobe** [comment]
this is duplicate of #445 ... btw: I am also building on windows

**Comment by janpio** [comment]
Thanks for confirming @simonobe, so we indeed have a Windows problem here: https://github.com/prisma/prisma-client-js/issues/445

**Comment by simonobe** [comment]
Is there any estimate? Can I contribute in any way? Do you at least have any idea on how to solve this?

**Comment by divyenduz** [comment]
In my understanding, this issue happens when the build machine is an OS without binary flags (like windows) and the deployment machine is a machine with binary flags. 

If you specify a binary provider in your Prisma schema file to download the binary for target platform OS, like in the case of netlify: 

`binaryTargets = ["native", "rhel-openssl-1.0.x"]`

The binary download happens with `prisma2 generate` on the build OS (windows). But the downloaded binary doesn't have any executable flag as it is on windows. 

When this binary is deployed a Prisma client attempts to run it, it fails. Most likely on [this line](https://github.com/prisma/prisma-client-js/blob/4e67206f85e43d9a06e082027f77fe7a1c7f1d95/packages/engine-core/src/NodeEngine.ts#L257). 

Next steps: We need to validate the above hypothesis and solve this in some way (already have +x flag on binaries in S3 or something)

**Comment by divyenduz** [comment]
> We need to validate the above hypothesis

I can confirm it. I tried deploying to Lambda from Windows are ran into this error. 

Now, we need to think of a way to fix this. Maybe, detecting lambda runtime, copying the binary to `/tmp`, adding the required flag and copying it back (or a variation of this is needed)

**Comment by kyunghoon** [comment]
i'm using lambda-layers to package the runtime which copies it into`/opt/` is there a configuration setting in prisma to specify the location of the binary?

**Comment by 422158** [comment]
> > We need to validate the above hypothesis
> 
> I can confirm it. I tried deploying to Lambda from Windows are ran into this error.
> 
> Now, we need to think of a way to fix this. Maybe, detecting lambda runtime, copying the binary to `/tmp`, adding the required flag and copying it back (or a variation of this is needed)

how do you intend to copy it back when it is read only fs

> i'm using lambda-layers to package the runtime which copies it into`/opt/` is there a configuration setting in prisma to specify the location of the binary?

yeah i think this guy might be onto something. i am not sure but i think that within lambda environemnt you can only change fs within /tmp... if we would be able to change/specify the binary location within prisma client, we might copy the binary to the /tmp, add execution rights and use this modified executable in client

**Comment by divyenduz** [comment]
> or a variation of this is needed

Yup, we can use the binary from `/tmp`, if needed.

**Comment by divyenduz** [comment]
You can also already configure custom binary paths and work around this: https://github.com/prisma/specs/tree/master/binaries#environment-variables

**Comment by janpio** [comment]
> > i'm using lambda-layers to package the runtime which copies it into`/opt/` is there a configuration setting in prisma to specify the location of the binary?
> 
> yeah i think this guy might be onto something. i am not sure but i think that within lambda environemnt you can only change fs within /tmp... if we would be able to change/specify the binary location within prisma client, we might copy the binary to the /tmp, add execution rights and use this modified executable in client

This is what Prisma Client could/should do itself possibly if it runs into the error message I specified in the issue title. Right now it fails if it can not set +x on the file. But trying to copy to `/tmp` might give us another way to fix this and thus also fix this issue in general.

We will look into this.

**Comment by divyenduz** [comment]
Listing down the potential workarounds for this: 

1. Use a CI/CD setup, Building your application in a *nix based OS with executable flags will work. 

2. Use custom binary paths [environment variables](https://github.com/prisma/specs/tree/master/binaries#environment-variables) and upload the binary to `/tmp` and alter its executable flag. When we fix this, this is probably we will do internally. 

3. Use lambda layers and make the binaries be available at a path. Use the path at runtime. Optionally, delete the uploading binaries to make the build smaller.

**Comment by kyunghoon** [comment]
following @divyenduz tip, i have set the environment variable `PRISMA_QUERY_ENGINE_BINARY` to point to the binary, in my case `/opt/runtime/query-engine-rhel-openssl-1.0.x`. but now i get a different and less useful error.

please let me know if there is anything i can do to help.

`{"errorType":"Error","errorMessage":"\nInvalid `prisma.users.create()` invocation in\n/var/task/index.js:5506:25\n\nNo such file or directory (os error 2)","stack":["Error: ","Invalid `prisma.users.create()` invocation in","/var/task/index.js:5506:25","","No such file or directory (os error 2)","    at PrismaClientFetcher.request (/var/task/index.js:4122:17)","    at processTicksAndRejections (internal/process/task_queues.js:94:5)"]}`

**Comment by janpio** [comment]
Please create a new issue for this @kyunghoon - we will look into it. Thanks.

**Comment by leungandrew** [comment]
I've experienced this issue when deploying a Nexus + Prisma app to serverless using the Serverless Express component.  Reading through the comments, it seems people have isolated it to be a `Windows` issue?  But I am also seeing this issue when compiling via darwin, and deploying with 
```
generator prisma_client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

**Comment by eddeee888** [comment]
I have got Prisma client working with Serverless Express component. Here's how:

1. Deploy a lambda layer containing only your Prisma client for. Here's a sample [Github Action on how to do it](https://github.com/eddeee888/base-app-monorepo/blob/e30fb7c422946e61fc394a3dabce662d80d81a31/.github/workflows/deploy-prisma-client-lambda-layer.yml#L31-L47)

2. Use the uploaded lambda layer ARN in your Express [serverless.yml](https://github.com/eddeee888/base-app-monorepo/blob/e30fb7c422946e61fc394a3dabce662d80d81a31/server/serverless.yml#L14-L16)

3. Check the Express Lambda function on AWS. If you can see that it uses the Prisma layer, it means it works!

( OPTIONAL ) It's better IMO to only install binary target based on the environment so the lambda layer is smaller. I normally [use env to install different binary](https://github.com/eddeee888/base-app-monorepo/blob/master/server/prisma/schema.prisma#L11), depending on the environment ( `native` for devs,  `rhel-openssl-1.0.x` when [building for prod](https://github.com/eddeee888/base-app-monorepo/blob/e30fb7c422946e61fc394a3dabce662d80d81a31/.github/workflows/deploy-server.yml#L32-L35) )

**Comment by divyenduz** [comment]
I am able to reproduce this thanks to the reproduction provided by @leungandrew (https://github.com/leungandrew/nexus-prisma-serverless-express)

It was previously established that this is a windows -> Linux issue but I am able to reproduce this between mac -> Linux. I also checked that the local binary before deployment has the +x flag

![image](https://user-images.githubusercontent.com/746482/85523654-e711c200-b624-11ea-9175-566af5d5c020.png)

**Comment by abelchee** [comment]
Copy to tmp folder works for me.

```
const binaryPath = '/tmp/query-engine-rhel-openssl-1.0.x';
if (!fs.existsSync(binaryPath)) {
  const { spawnSync } = require('child_process');

  spawnSync('cp', [
    `${process.env.LAMBDA_TASK_ROOT}/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x`,
    '/tmp/',
  ]);

  spawnSync('chmod', [`555`, '/tmp/query-engine-rhel-openssl-1.0.x']);
}
```

**Comment by samrith-s** [comment]
> Copy to tmp folder works for me.
> 
> ```
> const binaryPath = '/tmp/query-engine-rhel-openssl-1.0.x';
> if (!fs.existsSync(binaryPath)) {
>   const { spawnSync } = require('child_process');
> 
>   spawnSync('cp', [
>     `${process.env.LAMBDA_TASK_ROOT}/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x`,
>     '/tmp/',
>   ]);
> 
>   spawnSync('chmod', [`555`, '/tmp/query-engine-rhel-openssl-1.0.x']);
> }
> ```
> 
> And need an env:
> 
> ```
>   PRISMA_QUERY_ENGINE_BINARY: /tmp/query-engine-rhel-openssl-1.0.x
> ```

How and where are you running this? I am trying to deploy my nest application and got into the same issue.

**Comment by davidboom95** [comment]
> > Copy to tmp folder works for me.
> > ```
> > const binaryPath = '/tmp/query-engine-rhel-openssl-1.0.x';
> > if (!fs.existsSync(binaryPath)) {
> >   const { spawnSync } = require('child_process');
> > 
> >   spawnSync('cp', [
> >     `${process.env.LAMBDA_TASK_ROOT}/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x`,
> >     '/tmp/',
> >   ]);
> > 
> >   spawnSync('chmod', [`555`, '/tmp/query-engine-rhel-openssl-1.0.x']);
> > }
> > ```
> > 
> > 
> > And need an env:
> > ```
> >   PRISMA_QUERY_ENGINE_BINARY: /tmp/query-engine-rhel-openssl-1.0.x
> > ```
> 
> How and where are you running this? I am trying to deploy my nest application and got into the same issue.

+1

**Comment by samrith-s** [comment]
I've tried running this snippet in my lambda handler and have set the environment variable as well. But to no avail. 

I don't get any logs of this running, and I get an error saying it cannot find it in `/tmp`. Stuck very badly with this.

**Comment by davidboom95** [comment]
> I've tried running this snippet in my lambda handler and have set the environment variable as well. But to no avail.
> 
> I don't get any logs of this running, and I get an error saying it cannot find it in `/tmp`. Stuck very badly with this.

I'm using serverless-monorepo, so I'm having just one root prisma file and multiple `serverless.yml` services. Moving that 'schema.prisma' and 'query-engine-rhel-openssl-1.0.x' between folders is a nightmare

**Comment by samrith-s** [comment]
Are you using NestJS? Or webpack? If yes, I can share what I have done.

**Comment by davidboom95** [comment]
I solved it. I made a file with this code. This code gets executed on every lambda request. 
To get the file paths, I needed to debug and print folders and its contents to know where the files are.

```
const fs = require('fs');

const binaryPath = '/tmp/query-engine-rhel-openssl-1.0.x'

if (!fs.existsSync(binaryPath) && !process.env.IS_OFFLINE) {

  fs.copyFileSync(
    `${process.env.LAMBDA_TASK_ROOT}/query-engine-rhel-openssl-1.0.x`,
    binaryPath
  )
  
  fs.chmodSync(binaryPath, 555)

  process.env.PRISMA_QUERY_ENGINE_BINARY = binaryPath
}
```

**Comment by samrith-s** [comment]
@davidboom95 i would suggest using Lambda Layers (which is what I'm using) to greatly reduce bundle size and avoid doing this which also results in better startup times :)

**Comment by davidboom95** [comment]
Do you have the code? I tried to use a lambda layer but didn't know how to execute that preparation automatically

**Comment by samrith-s** [comment]
Yes. Can you message me on the Prisma Slack channel?
