### ISSUE TITLE
[self-referential relations] Attempted to serialize scalar with non-scalar compatible type 'List(Object((Weak)))

### ISSUE THREAD

**Issue by lukehamilton** [prisma/prisma-client-js#491]
Main Error Message
```
Attempted to serialize scalar with non-scalar compatible type 'List(Object((Weak)))
```

Schema
```
model Post {
  id            String    @default(cuid()) @id
  slug          String    @unique
  comments      Comment[] @relation(name: "postComments")
}

model Comment {
  id            String         @default(cuid())
  post          Post?          @relation(name: "postComments")
  parent        Comment?       @relation(name: "commentReplies")
  replies       Comment[]      @relation(name: "commentReplies")
}
```

Query
```
query post {
  post(slug: "hyperspektiv-2-0") {
    id
    comments {
      id
      replies {
        id
      }
    }
  }  
}
```
Error
```
Error: 
Invalid `var result_1 = (fieldResolver || graphql_1.defaultFieldResolver)()` invocation in
/Users/lukehamilton/development/lyra-labs-dev/lyra-labs/backend/node_modules/graphql-extensions/lib/index.js:119:77

  115 // If no resolver has been defined for a field, use the default field resolver
  116 // (which matches the behavior of graphql-js when there is no explicit resolve function defined).
  117 // TODO: Find a way to respect custom field resolvers, see https://github.com/graphql/graphql-js/pull/865
  118 try {
→ 119     var result_1 = (fieldResolver || graphql_1.defaultFieldResolver)(source, args, context, info)

Reason: Attempted to serialize scalar 'ck6d3v5uy01625bykrf7jj6oz' with non-scalar compatible type 'List(Object((Weak)))'

    at PrismaClientFetcher.request (/Users/lukehamilton/development/lyra-labs-dev/lyra-labs/backend/node_modules/@prisma/client/index.js:62:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
```
 {
  "data": {
    "post": null
  },
  "errors": [
    {
      "message": "\n\u001b[31mInvalid \u001b[1m`var result_1 = (fieldResolver || graphql_1.defaultFieldResolver)()`\u001b[22m invocation in\u001b[39m\n\u001b[31m\u001b[4m/Users/lukehamilton/development/lyra-labs-dev/lyra-labs/backend/node_modules/graphql-extensions/lib/index.js:119:77\u001b[24m\u001b[39m\n\n\u001b[2m  \u001b[90m115 \u001b[39m\u001b[90m// If no resolver has been defined for a field, use the default field resolver\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m116 \u001b[39m\u001b[90m// (which matches the behavior of graphql-js when there is no explicit resolve function defined).\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m117 \u001b[39m\u001b[90m// TODO: Find a way to respect custom field resolvers, see https://github.com/graphql/graphql-js/pull/865\u001b[39m\u001b[22m\n\u001b[2m  \u001b[90m118 \u001b[39m\u001b[36mtry\u001b[39m \u001b[38;2;107;139;140m{\u001b[39m\u001b[22m\n\u001b[31m\u001b[1m→\u001b[22m\u001b[39m \u001b[90m119 \u001b[39m    \u001b[36mvar\u001b[39m result_1 = \u001b[38;2;107;139;140m(\u001b[39mfieldResolver || graphql_1\u001b[38;2;107;139;140m.\u001b[39mdefaultFieldResolver\u001b[38;2;107;139;140m)\u001b[39m\u001b[38;2;107;139;140m(\u001b[39msource\u001b[38;2;107;139;140m,\u001b[39m args\u001b[38;2;107;139;140m,\u001b[39m context\u001b[38;2;107;139;140m,\u001b[39m info\u001b[38;2;107;139;140m)\u001b[39m\n\n\u001b[31m\u001b[1mReason: \u001b[22m\u001b[39m\u001b[31mAttempted to serialize scalar 'ck6d3v5uy01625bykrf7jj6oz' with non-scalar compatible type 'List(Object((Weak)))'\u001b[39m\n\u001b[31m\u001b[39m",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "post",
        "comments",
        0,
        "replies"
      ]
    }
  ]
}
```

<img height="300" src="https://p71.p4.n0.cdn.getcloudapp.com/items/L1ukL66m/Image+2020-02-07+at+11.46.36+PM.png" />

Seed
```
for (let j = minComments; j < maxComments; j += 1) {
  const author = usernames[Math.floor(Math.random() * usernames.length)];
  const parent = await prisma.comment.create({
    data: {
      author: { connect: { username: author } },
      post: { connect: { slug: postSlugs[i] } },
      text: COMMENT_PARENT_TEXT
    }
  });

  for (let k = minReplies; k < maxReplies; k += 1) {
    const replyAuthor = usernames[Math.floor(Math.random() * usernames.length)];
    const reply = await prisma.comment.create({
      data: {
        author: { connect: { username: replyAuthor } },
        text: COMMENT_REPLY_TEXT,
        parent: { connect: { id: parent.id } }
      }
    });
  }
}
```

**Comment by lukehamilton** [comment]
@pantharshit00 I pushed a fix. If you run it with the `docker-compose` file and PG you will be able to reproduce the issue. I believe you ran into the above error because it was using SQLite. I'm not sure why that is but it doesn't occur with PG (which I am using) and you can reproduce the issue now with the updated code I pushed:  https://github.com/lukehamilton/prisma-self-relations-test

**Comment by pantharshit00** [comment]
I will like to wait for https://github.com/prisma-labs/nexus-prisma/pull/608 so that I can test this out with preview022. Right now I can reproduce this with preview021 though.

**Comment by tre-dev** [comment]
I've tested it now with v22 and I think it works now! Let's wait for @lukehamilton to confirm.

**Comment by pantharshit00** [comment]
I can also no longer reproduce this with the reproduce that @lukehamilton shared with me. I used `prisma2@2.0.0-alpha.831, binary version: b1752e02f2f7d6243ce0171f7a357fbf6887083d` and nexus-prisma version `0.10.0`

**Comment by lukehamilton** [comment]
This is fixed for me now too with v22. Thanks!!!
