### ISSUE TITLE
Setting an array of scalar values

### ISSUE THREAD

**Issue by impowski** [prisma/prisma-client-js#494]
OS: `MacOS`
Prisma: `preview21`

I have a model which looks like this:
```prisma
model UserFilterTemplate {
  id               String    @id @default(uuid())
  user             User
  name             String
  originCity       String?
  originState      String?
  destinationCity  String?
  destinationState String?
  trailerTypes     String[]
  maxWeight        Int?
  loadType         LoadType?
}
```

I'm having a resolver which has all of the same fields and basically does this:

```ts
return await ctx.prisma.userFilterTemplate.create({
  data: {
    name,
    originCity,
    originState,
    destinationCity,
    destinationState,
    trailerTypes: {
      set: trailerTypes // <--- this is basically impossible and throws an error because I'm unable to set the value to null
    },
    maxWeight,
    loadType,
    user: {
      connect: {
        id: userId
      }
    }
  }
})
```

This is what's get generated by `@prisma/client`:
```ts
export declare type UserFilterTemplateCreatetrailerTypesInput = {
    set?: Enumerable<string> | null;
};
```

An error I get when `trailerTypes` is not passed to my resolver and basically undefined:
```console
server: TypeError: Cannot read property 'collectErrors' of null
server:     at errors.push.flatMap_1.flatMap (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9794:26)
server:     at Array.map (<anonymous>)
server:     at Object.flatMap (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:26373:26)
server:     at Arg.collectErrors (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9793:38)
server:     at flatMap_1.flatMap.arg (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9716:56)
server:     at Array.map (<anonymous>)
server:     at Object.flatMap (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:26373:26)
server:     at Args.collectErrors (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9716:26)
server:     at Arg.collectErrors (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9805:18)
server:     at flatMap_1.flatMap.arg (/Users/impowski/Projects/loaders/node_modules/@prisma/client/runtime/index.js:9716:56)
```

The current workaround:
```ts
return await ctx.prisma.userFilterTemplate.create({
  data: {
    name,
    originCity,
    originState,
    destinationCity,
    destinationState,
    trailerTypes: {
      set: trailerTypes || [] // I cannot do set it to null
    },
    maxWeight,
    loadType,
    user: {
      connect: {
        id: userId
      }
    }
  }
})
```

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/prisma-client-js/issues/459

**Comment by pantharshit00** [comment]
I can confirm the behaviour but I am not sure if this is a bug as scalar lists are not allowed to be null.

More minimal reproduction here: 
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  name String
  test String[]
}
```

```js
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  const data = await prisma.user.create({
    data: 
      name: "Harshit Pant",
      test: {
        set: null
      }
    }
  });
  console.log(data);
}

main();
```

**Comment by timsuchanek** [comment]
This is now handled with a better error:
```
{
  data: {
?   stringList?: BCreatestringListInput | String[],
+   id: String
  }
}

Argument stringList for data.stringList must not be null. Please use undefined instead.
Argument id for data.id is missing.

Note: Lines with + are required, lines with ? are optional.
```
