### ISSUE TITLE
Select record and chain more time then once

### ISSUE THREAD

**Issue by homoky** [prisma/prisma-client-js#552]
Hey, 

I've just found out that in the latest, but it occurred also in the previous versions, that there is no possibility for multiple chaining. 

Not working, but still expected:

```
const users = await prisma.campaign
              .findOne({ where: { id: campaign.id } })
              .supplier() // First ok
              .notifiedUsers(); // Second fails
```

Working:

```
const users = await prisma.campaign
              .findOne({ where: { id: campaign.id } })
              .supplier() // OK
              .then(supplier => // Have to fetch supplier manualy and then ok
                prisma.supplier
                  .findOne({
                    where: {
                      id: supplier.id,
                    },
                  })
                  .notifiedUsers() // This is working just fine
              );
```

**Comment by homoky** [comment]
Hey, 

here is part of schema:

```
generator photon {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("POSTGRES_URL")
}

model User {
  id                String     @id @default(cuid())
  firstName         String
  lastName          String
  email             String     @unique
  vendors           Vendor[]   @relation(name: "UserVendors")
  createdAt         DateTime   @default(now())
  updatedAt         DateTime   @updatedAt
}

model Vendor {
  id        String     @id @default(cuid())
  name      String     @unique
  users     User[]     @relation(name: "UserVendors")
  campaigns Campaign[] @relation(name: "VendorCampaigns")
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
}

model Campaign {
  id            String   @id @default(cuid())
  name          String
  scheduledFrom DateTime
  scheduledTo   DateTime
  enabled       Boolean
  vendor        Vendor   @relation(name: "VendorCampaigns")
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
}
```

I have for example this easy function that works:

```
import { prisma } from '../../../context';

type Props = {
  campaignId: string;
  userId: string;
};

const userHasAccessToCampaignAsVendor = async ({ campaignId, userId }: Props): Promise<boolean> =>
  await prisma.campaign
    .findOne({ where: { id: campaignId } })
    .sites()
    .then(async sites => {
      return Promise.all(
        sites.map(async site =>
          prisma.site
            .findOne({ where: { id: site.id } })
            .vendor()
            // TODO: try to refactor to: vendor().users()...
            .then(vendor => prisma.user.findMany({ where: { vendors: { some: { id: vendor.id } } } }))
            .then(users => users.filter(user => user.id === userId).length === 1)
        )
      );
    })
    .then(booleans => booleans.includes(true));

export default userHasAccessToCampaignAsVendor;
```

If I refactor it to:

```
import { prisma } from '../../../context';

type Props = {
  campaignId: string;
  userId: string;
};

const userHasAccessToCampaignAsVendor = async ({ campaignId, userId }: Props): Promise<boolean> => {
  try {
    return prisma.campaign
      .findOne({ where: { id: campaignId } })
      .sites()
      .then(async sites => {
        return Promise.all(
          sites.map(async site =>
            prisma.site
              .findOne({ where: { id: site.id } })
              .vendor()
              .users()
              .then(users => users.filter(user => user.id === userId).length === 1)
          )
        );
      })
      .then(booleans => booleans.includes(true));
  } catch (e) {
    console.log(e);
  }
};

export default userHasAccessToCampaignAsVendor;
```

It throws then:

```
Error: 
Invalid `prisma.select.vendor.select.users()` invocation:



Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "missing FROM-clause entry for table \"_UserVendors\"", detail: None, hint: None, position: Some(Original(32)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3236), routine: Some("errorMissingRTE") }) }) })

    at PrismaClientFetcher.request (/Users/homoky/Developer/posmonitoring/node_modules/@prisma/client/index.js:62:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Invalid `prisma.select.vendor.select.users()` invocation:



Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "missing FROM-clause entry for table \"_UserVendors\"", detail: None, hint: None, position: Some(Original(32)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3236), routine: Some("errorMissingRTE") }) }) })

    at PrismaClientFetcher.request (/Users/homoky/Developer/posmonitoring/node_modules/@prisma/client/index.js:62:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 
Invalid `prisma.select.vendor.select.users()` invocation:



Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "missing FROM-clause entry for table \"_UserVendors\"", detail: None, hint: None, position: Some(Original(32)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3236), routine: Some("errorMissingRTE") }) }) })

    at PrismaClientFetcher.request (/Users/homoky/Developer/posmonitoring/node_modules/@prisma/client/index.js:62:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have version: `^2.0.0-preview023`

**Comment by pantharshit00** [comment]
@homoky Can you please try again with `preview024` and see if this is fixed?

**Comment by homoky** [comment]
Hey.

Error is still there.

I refactored this: 

```
prisma.site
            .findOne({ where: { id: site.id } })
            .vendor()
            // TODO: try to refactor to: vendor().users()...
            .then(vendor => prisma.user.findMany({ where: { vendors: { some: { id: vendor.id } } } }))
            .then(users => users.filter(user => user.id === userId).length === 1)
```

to this: 

```
prisma.site
            .findOne({ where: { id: site.id } })
            .vendor()
            .users()
            .then(users => users.filter(user => user.id === userId).length === 1)
```

And now it throws an error.

**Comment by pantharshit00** [comment]
I tried this out with `2.0.0-beta.1` and converted your datamodel to follow new relation syntax via introspection. I was unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/78453913-54f7be80-76b2-11ea-9a5c-06e3b44a386f.png)

So can you please try this again with beta please 🙏 .

**Comment by homoky** [comment]
Hey. I tried beta 2 and it works well. Thanks.
