### ISSUE TITLE
Turn data length mismatch error into known (and better) error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#558]
Errors similar to this:
https://github.com/prisma/prisma-test-utils/issues/19

```
PrismaClientUnknownRequestError:
Invalid `: new departmentsClient()` invocation in
C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\employees\node_modules\prisma-client\index.js:535:7

   531   args || {},
   532   [],
   533   errorFormat,
   534   measurePerformance
→  535 ) : new departmentsClient

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1406, message: "Data too long for column \'dept_no\' at row 1", state: "22001" })) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\employees\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
PrismaClientUnknownRequestError:
Invalid `: new currenciesClient()` invocation in
C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\kanboard\node_modules\prisma-client\index.js:2735:7

  2731   args || {},
  2732   [],
  2733   errorFormat,
  2734   measurePerformance
→ 2735 ) : new currenciesClient

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1406, message: "Data too long for column \'currency\' at row 1", state: "22001" })) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\kanboard\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
PrismaClientUnknownRequestError:
Invalid `: new characterClient()` invocation in
C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\shakespeare\node_modules\prisma-client\index.js:805:7

   801   args || {},
   802   [],
   803   errorFormat,
   804   measurePerformance
→  805 ) : new characterClient

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("22001"), message: "value too long for type character varying(32)", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("d:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\varchar.c"), line: Some(636), routine: Some("varchar") }) }) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\shakespeare\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by tomhoule** [comment]
I think that would be something that needs to be done in the query engine. I could take this.

**Comment by tomhoule** [comment]
PR for this: https://github.com/prisma/prisma-engines/pull/622

Sadly postgres errors don't contain the name of the column with the mismatch, so we are only able to return a generic error there. On MySQL we do have the column name.

**Comment by tomhoule** [comment]
The PR is merged. I'll close this issue for now, because we can't give more information beyond what the database gives us. If someone wants to improve phrasing or has other ideas to improve the errors, please feel free to reopen.
