### ISSUE TITLE
Crash on querying a table which contains tsvector column

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma-client-js#571]
I've attempted to query all items in a postgres table. The table contains a column of type `tsvector`, which seems to be the cause of this crash.

```
(node:52874) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.article.findMany()` invocation in
/home/emi/Projects/prisma-playground/index.ts:5:16

  1 import { PrismaClient } from '@prisma/client'
  2 
  3 const prisma = new PrismaClient()
  4 
→ 5 prisma.article.findMany().then((x) => 

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(19), cause: Some(WrongType { postgres: TsVector, rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/home/emi/Projects/prisma-playground/node_modules/@prisma/client/runtime/index.js:1:47490)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:52874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please note that it's very uncommon fetch the value of `tsvector` columns, it is rather used for building full text indices.

Here is the table schema including an appropriate trigger for populating the `tsvector` column, for your convenience: 

```
CREATE TABLE public."Article" (
	title text NOT NULL,
	text_index tsvector NULL,
);
```

Version information:

```
$ /home/emi/Projects/prisma-playground/node_modules/.bin/prisma2 version
prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85
```

**Comment by janpio** [comment]
Excuse the naive question, but what should a `tsvector` value representation look like? Would returning a string representation similar to what is shown on https://www.postgresql.org/docs/12/datatype-textsearch.html solve your problem?

**Comment by ejoebstl** [comment]
To be honest, I would omit it in the output. 

tsvector columns are interesting for filtering and ranking the results, but I would guess most use cases don't require them in the client application. 

Otherwise, according to the documentation:

> A tsvector value is a sorted list of distinct lexemes, which are words that have been normalized to merge different variants of the same word.

And

> Optionally, integer positions can be attached to lexemes.

So a good representation would be an ordered list of key-value tuples, where the key is a string and the value is a list of integers.

**Comment by pantharshit00** [comment]
We show a warning in introspection about this:
![image](https://user-images.githubusercontent.com/22195362/79690712-742d4900-8279-11ea-99eb-b60caa1a4057.png)


I think it will take some time before we can add support for these types.
