### ISSUE TITLE
Unable to resolve a primary identifier for model 'x'

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#587]
(This is a follow up investigation to https://github.com/prisma/prisma-client-js/issues/529)

 

## Bug description

Some database tables return the following error on query: 

```
PANIC: Unable to resolve a primary identifier for model <model-name>
```

## How to reproduce

Import this SQL into a local MySQL database: 

```sql
-- MySQL dump 10.13  Distrib 5.7.27, for osx10.14 (x86_64)
--
-- Host: 127.0.0.1    Database: nextcloud
-- ------------------------------------------------------
-- Server version	5.7.29

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `jvMDv_collres_accesscache`
--

DROP TABLE IF EXISTS `jvMDv_collres_accesscache`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jvMDv_collres_accesscache` (
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `collection_id` bigint(20) DEFAULT '0',
  `resource_type` varchar(64) COLLATE utf8mb4_bin DEFAULT '',
  `resource_id` varchar(64) COLLATE utf8mb4_bin DEFAULT '',
  `access` tinyint(1) NOT NULL DEFAULT '0',
  UNIQUE KEY `collres_unique_user` (`user_id`,`collection_id`,`resource_type`,`resource_id`),
  KEY `collres_user_res` (`user_id`,`resource_type`,`resource_id`),
  KEY `collres_user_coll` (`user_id`,`collection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `jvMDv_collres_accesscache`
--

LOCK TABLES `jvMDv_collres_accesscache` WRITE;
/*!40000 ALTER TABLE `jvMDv_collres_accesscache` DISABLE KEYS */;
/*!40000 ALTER TABLE `jvMDv_collres_accesscache` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-03-19 19:20:26
```

Introspect this database and run: 

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const data = await prisma.jvMDv_collres_accesscache.findMany()
  console.log(data)
}

main()
```

Error: 

```
(node:27332) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.jvMDv_collres_accesscache.findMany()` invocation in
/Users/divyendusingh/Documents/prisma/p2-nextcloud/r.js:6:55

PANIC: Unable to resolve a primary identifier for model jvMDv_collres_accesscache.
    at PrismaClientFetcher.request (/Users/divyendusingh/Documents/prisma/p2-nextcloud/node_modules/@prisma/client/runtime/index.js:1:48880)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:27332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error in Prisma Client:
PANIC: Unable to resolve a primary identifier for model jvMDv_collres_accesscache. in
libs/prisma-models/src/model.rs:90:30

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.

```

## Expected behavior

It should work or fail gracefully

## Prisma information 

```
Prisma CLI Version   : prisma2@2.0.0-alpha.935
Current platform     : darwin
Query Engine         : prisma 6aa23a61c78a5418a0231347458d639aa337ec1d (at /Users/divyendusingh/Documents/prisma/p2-nextcloud/node_modules/prisma2/query-engine-darwin)
Migration Engine     : migration-engine-cli 6aa23a61c78a5418a0231347458d639aa337ec1d (at /Users/divyendusingh/Documents/prisma/p2-nextcloud/node_modules/prisma2/migration-engine-darwin)
Introspection Engine : introspection-core 6aa23a61c78a5418a0231347458d639aa337ec1d (at /Users/divyendusingh/Documents/prisma/p2-nextcloud/node_modules/prisma2/introspection-engine-darwin)

```

## Environment & setup

- OS: Mac OS Catalina
- Database: MySQL (but applies to others)

**Comment by janpio** [comment]
Simpler reproduction:

```sql
CREATE TABLE IF NOT EXISTS `foo` (
  `one` int(11) DEFAULT NULL,
  `two` int(11) DEFAULT NULL,
  UNIQUE KEY `Index 1` (`one`,`two`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

```prisma
model foo {
  one Int?
  two Int?

  @@unique([one, two], name: "Index 1")
}
```

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const data = await prisma.foo.findMany()
  console.log(data)
}

main()
```

```
Invalid `prisma.foo.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\587\index.js:6:33

PANIC: Unable to resolve a primary identifier for model foo.
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\587\node_modules\@prisma\client\runtime\index.js:1:48880)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:32884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error in Prisma Client:
PANIC: Unable to resolve a primary identifier for model foo. in
libs/prisma-models/src/model.rs:90:30

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
```

**Comment by janpio** [comment]
Seems to have to do with the `NULL` of the columns, not reproducible for:

```sql
CREATE TABLE IF NOT EXISTS `foo` (
  `one` int(11) NOT NULL,
  `two` int(11) NOT NULL,
  UNIQUE KEY `Index 1` (`one`,`two`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

which is

```prisma
model foo {
  one Int
  two Int

  @@unique([one, two], name: "Index 1")
}
```

**Comment by janpio** [comment]
This is currently a concious limitation, that we need to work around with a guardrail: https://github.com/prisma/prisma2/issues/1880

**Comment by divyenduz** [comment]
This is still reproducible with: 

```
divyendusingh [p2-587]$ yarn prisma2 --version
yarn run v1.21.1
$ /Users/divyendusingh/Documents/prisma/p2-587/node_modules/.bin/prisma2 --version
@prisma/cli          : 2.0.0-alpha.990
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/divyendusingh/Documents/prisma/p2-587/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/divyendusingh/Documents/prisma/p2-587/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/divyendusingh/Documents/prisma/p2-587/node_modules/@prisma/cli/introspection-engine-darwin)
✨  Done in 0.79s.

```

**Comment by divyenduz** [comment]
Closing this in favor of https://github.com/prisma/prisma-client-js/issues/529, they represent the same thing.

**Comment by do4gr** [comment]
This is now fixed by aligning the unique criteria the engines accept. All fields need to be not null.
