### ISSUE TITLE
Prisma client panics when unique constraints are violated

### ISSUE THREAD

**Issue by Nikxt** [prisma/prisma-client-js#593]
## Bug description

If a mutation breaks unique constraints, prisma client panics. No query and mutation works anymore until server restart.

## How to reproduce

1. Use `@unique` in schema on field (Product name)

```
model Product{
  id                    String             @default(cuid()) @id
  name              String             @unique
  description     String?
}
```

2. Setup createProduct resolver

```
export const createProduct = async (args: ProductCreateInput, ctx: ApolloContext) => {
  const data = { name: args.name};
  const createdProduct = await ctx.prisma.product.create({
    data
  });
  return createdProduct ;
};
```

3. Invoke a create mutation with a name for Product (name: Testname)

4. Invoke a second create mutation with the same name for Product (name: Testname)

5. See error 

<img width="571" alt="Prisma Panic" src="https://user-images.githubusercontent.com/35074943/77303562-75f40300-6cf3-11ea-93bc-c8bcd463bd3b.PNG">

6. Invoke other prisma queries or mutations

7. See following error

<img width="993" alt="Prisma Panic 2" src="https://user-images.githubusercontent.com/35074943/77303569-77bdc680-6cf3-11ea-9bf2-a7e1ef28994e.PNG">

## Expected behavior
Error after step 4 should be thrown but prisma-client should still work. 

## Prisma information 
If necessary, I will send the schema per email. I get the same error with every new type I created to test the problem.

## Environment & setup
- OS: Windows
- Database: PostgreSQL
- Prisma version: prisma2@2.0.0-preview023
- Node.js version: v12.13.0

**Comment by janpio** [comment]
I can not confirm this on a plain Prisma setup:

```sql
CREATE TABLE public."Product" (
	description text NULL,
	id text NOT NULL,
	name text NOT NULL DEFAULT ''::text,
	CONSTRAINT "Product_pkey" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "Product.name" ON public."Product" USING btree (name);
```

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

prisma.product.create({ data: { name: 'Foo' } }).then(res => { console.log(res) })
```

leads to

```
C:\Users\Jan\Documents\throwaway\593>node index.js
{ id: 'ck84t4vx40000hgs2cfdsd0sp', name: 'Foo', description: null }
^C
C:\Users\Jan\Documents\throwaway\593>node index.js
(node:26944) UnhandledPromiseRejectionWarning: Error: 
Invalid `data: { name: 'Foo' } }).then(res => { console.log()` invocation in
C:\Users\Jan\Documents\throwaway\593\index.js:5:16

  1 const { PrismaClient } = require('@prisma/client')
  2 
  3 const prisma = new PrismaClient()
  4 
→ 5 prisma.product.create(

Unique constraint failed on the fields: (`name`)
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\593\node_modules\@prisma\client\index.js:87:17)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:26944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
C:\Users\Jan\Documents\throwaway\593>node index.js
(node:32088) UnhandledPromiseRejectionWarning: Error: 
Invalid `data: { name: 'Foo' } }).then(res => { console.log()` invocation in
C:\Users\Jan\Documents\throwaway\593\index.js:5:16

  1 const { PrismaClient } = require('@prisma/client')
  2 
  3 const prisma = new PrismaClient()
  4 
→ 5 prisma.product.create(

Unique constraint failed on the fields: (`name`)
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\593\node_modules\@prisma\client\index.js:87:17)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:32088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
C:\Users\Jan\Documents\throwaway\593>node index.js
(node:23648) UnhandledPromiseRejectionWarning: Error: 
Invalid `data: { name: 'Foo' } }).then(res => { console.log()` invocation in
C:\Users\Jan\Documents\throwaway\593\index.js:5:16

  1 const { PrismaClient } = require('@prisma/client')
  2 
  3 const prisma = new PrismaClient()
  4 
→ 5 prisma.product.create(

Unique constraint failed on the fields: (`name`)
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\593\node_modules\@prisma\client\index.js:87:17)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:23648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I missing something @Nikxt?

**Comment by Nikxt** [comment]
It looks like our approach.
The only difference is that we instantiate the prisma client once at startup and pass it via the context.

The PANIC message is the same for any mutation that violates a unique constraint and every following query/mutation:
`PANIC: index out of bounds: the len is 1 but the index is 1 [...]` (Screenshots)

I also tried it with preview20.3 and got the same problem but without the error messages.

We are also using nexus 0.12.0-rc.13 and nexus-prisma 0.11.1

**Comment by janpio** [comment]
Hm, what do I need to do to reproduce this? Can you maybe create a reproduction repository based on my code and add things until it breaks in the described way?

**Comment by Nikxt** [comment]
Here is the repository: [https://github.com/Nikxt/unique-panic-reproduction](https://github.com/Nikxt/unique-panic-reproduction).

Basic setup: index.js file with a function to create a new product.

Global prisma version is `prisma2@2.0.0-preview023`

The following screenshot shows two executions of the index.js file
first: Product was created.
second: Prisma Panic.

<img width="590" alt="basic reproduction" src="https://user-images.githubusercontent.com/35074943/77898331-4311b800-727b-11ea-8c1e-7b21d4dba135.PNG">

**Comment by pantharshit00** [comment]
I was unable to reproduce this with ``:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22195362/78141181-be749480-7448-11ea-8752-bb92c61b0042.png">


Can you please try again this with that version?

**Comment by Nikxt** [comment]
I solved the problem by using a docker container for my postgres installation. Before that i used postgres directly as a windows installation. 

There was no other case that caused a problem with my postgres installation.

**Comment by pantharshit00** [comment]
@Nikxt Can you please tell me which PG version you were using on Windows?

**Comment by Nikxt** [comment]
Had this problem on two devices with Postgres for Windows.  
I've also tried prisma beta, but the problem was still there.
Device 1: PG version 12.1.3
Device 2: PG version 12.2.2

**Comment by Sytten** [comment]
Did the rust engine crashed completely? Has discussed with @timsuchanek, you are supposed to be able to still query even if a panic occurred for this request? I cam curious because I am working on auto-restart helpers to avoid this exact problem (one query killing the whole service)

**Comment by timsuchanek** [comment]
Closing this due to inactivity.
