### ISSUE TITLE
PostgreSQL: "PANIC: column on null constraint violation error in /root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/a1decce/src/connector/postgres/error.rs:67:35"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-client-js#609]
A PostgreSQL column on null constraint violation error leads to panic.

```sql
CREATE TABLE "public"."User" (
  id SERIAL PRIMARY KEY,
  name TEXT
);

CREATE TABLE "public"."Post" (
  id SERIAL PRIMARY KEY,
  title TEXT,
  "authorId" INTEGER,
  CONSTRAINT author FOREIGN KEY ("authorId") REFERENCES "public"."User" (id) ON DELETE RESTRICT
);
```

```schema
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  authorId Int?
  id       Int     @default(autoincrement()) @id
  title    String?
  User     User?   @relation(fields: [authorId], references: [id])
}

model User {
  id   Int     @default(autoincrement()) @id
  name String?
  Post Post[]
}
```

```js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const userWithPost = await prisma.user.create({
    data: {
      name: 'Alice',
      Post: {
        create: { title: 'Hello World' },
      },
    },
  });

  try {
    const deletedUser = await prisma.user.delete({
      where: { id: userWithPost.id },
    });
  } catch (e) {
    console.log(e);
  }
}

main();
```

leads to

```
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql>node index.js
PrismaClientUnknownRequestError:
Invalid `const deletedUser = await prisma.user.delete()` invocation in
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\index.js:16:49

  12   },
  13 });
  14
  15 try {
→ 16   const deletedUser = await prisma.user.delete(

PANIC: column on null constraint violation error
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error in Prisma Client:
PANIC: column on null constraint violation error in
/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/a1decce/src/connector/postgres/error.rs:67:35

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
```

```
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql>set DEBUG=*

C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql>node index.js
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: 'C:\\Users\\Jan\\Documents\\prisma2-docs-demos\\cascading-deletes\\postgresql\\prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: 'C:\\Users\\Jan\\Documents\\prisma2-docs-demos\\cascading-deletes\\postgresql\\node_modules\\@prisma\\client\\schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     datasources: [],
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: 'C:\\Users\\Jan\\Documents\\prisma2-docs-demos\\cascading-deletes\\postgresql\\node_modules\\@prisma\\client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     env: {
  prisma-client       DATABASE_URL: 'postgresql://postgres:prisma@localhost:5432/CascadingDeletesDemo?schema=public'
  prisma-client     },
  prisma-client     flags: []
  prisma-client   }
  prisma-client } +0ms
  prisma-client Prisma Client call: +82ms
  prisma-client prisma.user.create({
  prisma-client   data: {
  prisma-client     name: 'Alice',
  prisma-client     Post: {
  prisma-client       create: {
  prisma-client         title: 'Hello World'
  prisma-client       }
  prisma-client     }
  prisma-client   }
  prisma-client }) +22ms
  prisma-client Generated request: +5ms
  prisma-client mutation {
  prisma-client   createOneUser(data: {
  prisma-client     name: "Alice"
  prisma-client     Post: {
  prisma-client       create: [
  prisma-client         {
  prisma-client           title: "Hello World"
  prisma-client         }
  prisma-client       ]
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     name
  prisma-client   }
  prisma-client }
  prisma-client  +1ms
  getos { platform: 'win32', libssl: undefined } +0ms
  engine {
  engine   PRISMA_DML_PATH: 'C:\\Users\\Jan\\Documents\\prisma2-docs-demos\\cascading-deletes\\postgresql\\node_modules\\@prisma\\client\\schema.prisma',
  engine   PORT: '61981',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[]'
  engine } +0ms
  engine {
  engine   cwd: 'C:\\Users\\Jan\\Documents\\prisma2-docs-demos\\cascading-deletes\\postgresql\\prisma'
  engine } +26ms
  engine { flags: [ '--enable-raw-queries' ] } +4ms
  engine stderr Printing to stderr for debugging +77ms
  engine stdout {
  timestamp: 'Mar 30 01:38:16.291',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with 9 connections.' }
} +6ms
  engine stderr Listening on 127.0.0.1:61981 +25ms
  engine stdout {
  timestamp: 'Mar 30 01:38:16.305',
  level: 'INFO',
  target: 'prisma::server',
  fields: {
    message: 'Started http server on 127.0.0.1:61981',
    'log.target': 'prisma::server',
    'log.module_path': 'prisma::server',
    'log.file': 'query-engine/prisma/src/server.rs',
    'log.line': 109
  }
} +1ms
  prisma-client Prisma Client call: +279ms
  prisma-client prisma.user.delete({
  prisma-client   where: {
  prisma-client     id: 5
  prisma-client   }
  prisma-client }) +2ms
  prisma-client Generated request: +2ms
  prisma-client mutation {
  prisma-client   deleteOneUser(where: {
  prisma-client     id: 5
  prisma-client   }) {
  prisma-client     id
  prisma-client     name
  prisma-client   }
  prisma-client }
  prisma-client  +1ms
  engine stdout {
  timestamp: 'Mar 30 01:38:16.486',
  level: 'ERROR',
  target: 'prisma',
  fields: {
    message: 'PANIC',
    reason: 'column on null constraint violation error',
    file: '/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/a1decce/src/connector/postgres/error.rs',
    line: 67,
    column: 35
  }
} +163ms
  engine {
  engine   error: Error: read ECONNRESET
  engine       at TCP.onStreamRead (internal/stream_base_commons.js:183:27) {
  engine     errno: 'ECONNRESET',
  engine     code: 'ECONNRESET',
  engine     syscall: 'read'
  engine   }
  engine } +38ms
  printStack callsite Error
    at Object.s [as User] (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\node_modules\@prisma\client\runtime\index.js:1:48553)
    at Object.n.<computed> [as delete] (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\node_modules\@prisma\client\runtime\index.js:1:50179)
    at main (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\index.js:16:49)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) +0ms
PrismaClientUnknownRequestError:
Invalid `const deletedUser = await prisma.user.delete()` invocation in
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\index.js:16:49

  12   },
  13 });
  14
  15 try {
→ 16   const deletedUser = await prisma.user.delete(

PANIC: column on null constraint violation error
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\postgresql\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error in Prisma Client:
PANIC: column on null constraint violation error in
/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/a1decce/src/connector/postgres/error.rs:67:35

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
```

expected (per the docs) would be a bit les panicky (but still complicated) error message:

```
PrismaClientUnknownRequestError:
Invalid `const deletedUser = await prisma.user.delete()` invocation in
/Users/janedoe/cascasing-deletes-demo/index.js:16:49

  12   },
  13 })
  14
  15 try {
→ 16   const deletedUser = await prisma.user.delete(Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("23503"), message: "update or delete on table \"User\" violates foreign key constraint \"Post_author_fkey\" on table \"Post\"", detail: Some("Key (id)=(8) is still referenced from table \"Post\"."), hint: None, position: None, where_: None, schema: Some("public"), table: Some("Post"), column: None, datatype: None, constraint: Some("Post_author_fkey"), file: Some("ri_triggers.c"), line: Some(3280), routine: Some("ri_ReportViolation") }) }) })
    at PrismaClientFetcher.request (/Users/nikolasburk/Desktop/unique/cascasing-deletes-demo/node_modules/@prisma/client/index.js:89:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

---

```
λ prisma2 -v
@prisma/cli          : 2.0.0-alpha.982
Current platform     : windows
Query Engine         : prisma 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 45b377205ba60322a5e016dd1e43206270f7cef5 (at C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\introspection-engine-windows.exe)
```

**Comment by pantharshit00** [comment]
I can confirm this. 

Version used:
```
@prisma/cli          : 2.0.0-beta.1
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by MaxAst** [comment]
just to clarify, is this issue about that it's currently not possible to perform cascade deletes?

**Comment by janpio** [comment]
No, this is about "A PostgreSQL column on null constraint violation error leads to panic." which it should not.

**Comment by MaxAst** [comment]
okay cool, sorry didn't see the second bit

**Comment by pimeys** [comment]
This doesn't seem to panic anymore, but you'll still get an error: 

```json
{
  "errors": [
    {
      "error": "Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Index(\"author\") } })",
      "user_facing_error": {
        "is_panic": false,
        "message": "Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Index(\"author\") } })",
        "backtrace": null
      }
    }
  ]
}
```

**Comment by pimeys** [comment]
But. We for some reason don't throw a known user-facing error. So I'll do a PR for that, because we have a code for this!
