### ISSUE TITLE
"Error parsing GraphQL query" with a model named "Query"

### ISSUE THREAD

**Issue by ROiPinheiro** [prisma/prisma-client-js#627]
# Bug description

I got a "Error parsing GraphQL query" when doing "findMany()" with a model named "Query".

Repo to reproduce error:
https://github.com/ROiPinheiro/prisma-bug

## Debug log
```
prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/home/rafael/Projects/prisma-bug/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     datasources: [],
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/home/rafael/Projects/prisma-bug/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     env: { DATABASE_URL: 'mysql://root:root@localhost:3306/testdb' },
  prisma-client     flags: []
  prisma-client   }
  prisma-client } +0ms
  prisma-client Prisma Client call: +14ms
  prisma-client prisma.query.findMany(undefined) +0ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManyQuery {
  prisma-client 
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine {
  engine   PRISMA_DML_PATH: '/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/schema.prisma',
  engine   PORT: '41473',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[]'
  engine } +0ms
  engine { cwd: '/home/rafael/Projects/prisma-bug/prisma' } +0ms
  getos { version: 'OpenSSL 1.1.1c  28 May 2019\n' } +0ms
  getos { ls: '' } +0ms
  getos { platform: 'linux', libssl: '1.1.x' } +9ms
  plusX Execution permissions of /home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x are fine +0ms
  engine { flags: [ '--enable-raw-queries' ] } +14ms
  engine stderr Printing to stderr for debugging +27ms
  engine stderr Listening on 127.0.0.1:41473 +0ms
  engine stdout {
  timestamp: 'Apr 02 15:47:53.188',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a mysql pool with 9 connections.' }
} +1ms
  engine stdout {
  timestamp: 'Apr 02 15:47:53.192',
  level: 'INFO',
  target: 'prisma::server',
  fields: {
    message: 'Started http server on 127.0.0.1:41473',
    'log.target': 'prisma::server',
    'log.module_path': 'prisma::server',
    'log.file': 'query-engine/prisma/src/server.rs',
    'log.line': 109
  }
} +3ms
  engine {
  engine   error: PrismaClientUnknownRequestError: Error parsing GraphQL query: query parse error: Parse error at 4:3
  engine   Unexpected `}[Punctuator]`
  engine   Expected `Name`
  engine   
  engine       at NodeEngine.graphQLToJSError (/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:18851)
  engine       at /home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:16338
  engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  engine       at Dataloader.loader (/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:50647)
  engine } +9ms
  printStack callsite Error
    at Object.s [as Query] (/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:48551)
    at Object.n.<computed> [as findMany] (/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:50177)
    at test (/home/rafael/Projects/prisma-bug/index.js:7:40)
    at Object.<anonymous> (/home/rafael/Projects/prisma-bug/index.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 +0ms
PrismaClientUnknownRequestError: 
Invalid `prisma.query.findMany()` invocation in
/home/rafael/Projects/prisma-bug/index.js:7:40

Error parsing GraphQL query: query parse error: Parse error at 4:3
Unexpected `}[Punctuator]`
Expected `Name`

    at PrismaClientFetcher.request (/home/rafael/Projects/prisma-bug/node_modules/@prisma/client/runtime/index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

## Expected behavior

Return a list of "queries"

```js
[
  {
    "id": 1,
    "name: "test"
  }
]
```

## Prisma information

```ts
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Query {
  id   Int    @default(autoincrement()) @id
  name String

  @@map("query")
}
```

```js
const queries = await prisma.query.findMany();
```
## Environment & setup

- OS: Ubuntu 19.10
- Database: MySQL
- Prisma version: 2.0.0-beta.1
- Node.js version: 13.11.0

**Comment by pantharshit00** [comment]
Hi @ROiPinheiro,

Sorry for the late reply here. I can confirm this bug. The problem here is that you are using `Query` the model name which is conflicting the with internal wire protocol that client uses to communicate with the binaries. The internal protocol is GraphQL like so Query is kind of a reserved word in that. 

So we need to add Query in the denylist. As a workaround, you can change the name of the model.

**Comment by pantharshit00** [comment]
The schema used for reproduction:
```prisma
model Query {
  id   Int    @default(autoincrement()) @id
  name String

  @@map("query")
}
```

Then try calling prisma client against the query model.


Version used: 
```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.npm/_npx/73122/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.npm/_npx/73122/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.npm/_npx/73122/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by mavilein** [comment]
We added reserved GraphQL words to our schema validation. Models named `Query` are now forbidden. Implemented in: https://github.com/prisma/prisma-engines/commit/3cd2e8691906b5d6be11fe6e7e154f2a9928b6ff

PS: Since we are using a GraphQL parser internally there is no way how we can lift this restriction at the moment. We will revisit when we have our own custom protocol.
