### ISSUE TITLE
DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")

### ISSUE THREAD

**Issue by chrisjaimes** [prisma/prisma-client-js#629]
I am not able to create new users with mutations in the graphql playground with nexus@next and I got the following error message: 

`Invalid `prisma.user.create()` invocation in\n/node_modules/nexus-prisma/src/builder.ts:315:20\n\nError occurred during query execution:\nInterpretationError(\"Error for binding \\'2\\': DomainError(ConversionFailure(\\\"record identifier\\\", \\\"assimilated record identifier\\\"))\")`

My schema looks like this:

```
model Post {
  id String @id
}
model User {
  id        String   @id
  birthDate DateTime
  email     String   @unique
  posts     Post
}
```

GraphQL Mutation

```
mutation {
  createOneUser(data: {
    id: "test"
    email: "test@email.com"
    birthDate: "2015-11-22T13:57:31.123Z"
    posts: {
    create: {
      	id: "postId"
    	}
    }
  }) { 
  	id
       email
  }
}
```

**Comment by Pixselve** [comment]
I have the same mistake with the model:

```
model Contract {
  id Int @id @default(autoincrement())
  date DateTime @unique
  skills Skill[] @relation(references: [id])
}

model Skill {
  id Int @id @default(autoincrement())
  name String
  contract Contract @relation(fields: [contractId], references: [id])
  contractId Int
}
```

With the query :
```
prisma.contract.create({
    data: {
      date: new Date(),
      skills: {
        create: {
          name: "lorem ipsum"
        }
      }
    }
  });
```

I have the error:
```
Error occurred during query execution:
InterpretationError("Error for binding \'3\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")
    at PrismaClientFetcher.request (..........\@prisma\client\runtime\index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by janpio** [comment]
Please have a look at https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1 to upgrade your schema to the format that is required here.

**Comment by pantharshit00** [comment]
@chrisjaimes 2.0.0-beta.2 should now give you a proper validation error when you try to deploy that datamodel.

Please try using that now.

**Comment by timsuchanek** [comment]
Closing due to inactivity.
