### ISSUE TITLE
Multi relations in query

### ISSUE THREAD

**Issue by gothdawid** [prisma/prisma-client-js#633]
I would like it to create a poem with 4 accounts, unfortunately I have some mistake in every possible way.
I was cleaning the database.
I deleted migrations and created them again.
after uploading the schema and run "prisma introspect" disappear all relations with the schema.

**Error**
```
PANIC: assertion failed: index < len in

Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called
```

**prisma SQL**
```  
prisma.options.create({
        data: {
          file:{
            create: {
              name: args.filename,
            },
          },
          Routes: {
            create: {
              index: args.routename,
            },
          },
          Car:{
            create: {
              carnumber: args.carnumber,
            },
          },
          Value:{
            create: {
              value: args.value,
            },
          },
        },
      }),
```

**schema.prisma**
```generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Car {
  id            Int           @default(autoincrement()) @id
  carnumber     Int           @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]  

}

model File {
  id            Int           @default(autoincrement()) @id
  name          String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]  
}

model Routetovalue {
  id            Int           @default(autoincrement()) @id
  index         String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]    
}

model Values {
  id            Int           @default(autoincrement()) @id
  value         String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]    
}


model Options {
  id            Int           @default(autoincrement()) @id
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  routeName     String?
  Routes        Routetovalue?  @relation(fields: [routeName], references: [index])
  fileName      String?
  file          File?          @relation(fields: [fileName], references: [name])
  carnr         Int?
  Car           Car?           @relation(fields: [carnr], references: [carnumber])
  val           String?
  Value         Values?        @relation(fields: [val], references: [value])
}
```

**package.json**
```
{
  "name": "graphql-expres-API",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon --exec babel-node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nexus/schema": "^0.13.1",
    "@prisma/client": "^2.0.0-beta.1",
    "@types/node-fetch": "^2.5.5",
    "apollo-server": "^2.11.0",
    "babel-cli": "^6.26.0",
    "babel-preset-latest": "^6.24.1",
    "fs": "0.0.1-security",
    "graphql": "^14.6.0",
    "nexus": "^0.12.0",
    "nexus-prisma": "^0.12.0",
    "pg": "^7.18.2"
  },
  "devDependencies": {
    "@prisma/cli": "^2.0.0-beta.1",
    "@types/node": "^13.11.0",
    "eslint": "^6.8.0",
    "eslint-config-google": "^0.14.0",
    "ts-node": "^8.8.1",
    "typescript": "^3.8.3"
  },
  "prettier": {
    "singleQuote": true,
    "semi": false,
    "trailingComma": "all"
  }
}

```

- OS: Windows and Ubuntu 
- Database: PostgreSQL - REMOTE
- Prisma version: 2.0.0-beta.2
- Node.js version: 12.30.0

**Comment by gothdawid** [comment]
**After rebuilding the schema**

**error from studio**
```
Error in Prisma Client request: 

Error: 
Invalid `prisma.car.findMany()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "BŁĄD", parsed_severity: Some(Error), code: SqlState("42601"), message: "błąd składni w lub blisko \")\"", detail: None, hint: None, position: Some(Original(131)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1133), routine: Some("scanner_yyerror") }) }) })
    at PrismaClientFetcher.request (C:\Users\dawid\AppData\Roaming\Prisma\Studio\-Visual_Code-MZKAutobusDBAPI\runtime\index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```


**schema**
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Car {
  id            Int           @default(autoincrement()) @id
  carnumber     Int           @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]  

}

model File {
  id            Int           @default(autoincrement()) @id
  name          String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]  
}

model Routetovalue {
  id            Int           @default(autoincrement()) @id
  index         String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]    
}

model Values {
  id            Int           @default(autoincrement()) @id
  value         String        @unique
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  opts       Options[]    
}


model Options {
  id            Int           @default(autoincrement()) @id
  createdAt     DateTime?     @default(now())
  updatedAt     DateTime?     @default(now())
  Routes        Routetovalue? @relation(references: [index])
  file          File?         @relation(references: [name])
  Car           Car?          @relation(references: [carnumber])
  Value         Values?       @relation(references: [value])
}
```

**Comment by gothdawid** [comment]
**Reproduce**

1. download https://mega.nz/file/nx5FSToS#awDQC8o76fmNug-EIWiZ8BTDoYdlmfOJRKzbbTDCqPs
2. unpack
3. npx prisma migrate save --experimental
4. npx prisma migrate up --experimental
5. npx prisma generate
6. npx prisma studio --experimental or try prisma.option.create in resolvers.js

**Comment by gothdawid** [comment]
After upgrading to beta.2, the problem persists

**Comment by nilaeus** [comment]
I've been having a lot of funky issues with multi-relations, but the issue that I mentioned this one in (above) brought me to the same error of panic.

In my case, creating the model that has the problem from the query errors this way, but nested within another query simply ignores its creation, but makes the nested creations.

**Comment by pantharshit00** [comment]
I can reproduce this issue, here is a minimal reproduction: https://github.com/harshit-test-org/prisma-client-633

We will need to fix this.

**Comment by dpetrick** [comment]
I pinned the issue, however, it's fairly complicated. Will update the issue once a fix is available.

**Comment by dpetrick** [comment]
A fix is available on alpha-1141 onwards. Please validate that it works for you now.

**Comment by gothdawid** [comment]
> A fix is available on alpha-1141 onwards. Please validate that it works for you now.

Yes, it's works! :D
