### ISSUE TITLE
Client broken when deployed via serverless-next.js

### ISSUE THREAD

**Issue by vaskevich** [prisma/prisma-client-js#677]
Hi, I wanted to file an issue for this here since the [`rest-nextjs` example](https://github.com/prisma/prisma-examples/tree/master/typescript/rest-nextjs) is linked from the home page of prisma.io, and next.js supports [serverless deployment](https://www.serverless.com/blog/serverless-nextjs/) as an official feature. If there's a workaround, hopefully it will help anyone else who's trying to deploy Prisma with Next.js via Serverless.

To extend this example, I added the `serverless` and `serverless-next.js` packages, along with the following `serverless.yml` file:

```yml
example:
    component: serverless-next.js
```

and then updated `schema.prisma` to add the binary target for Lambda:

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

When I run `serverless`, the deployment goes through, but the pages and API endpoints start returning 500s. Here's the error I get in my AWS Lambda logs:

`ERROR Error: Invalid 'prisma.post.findMany()' invocation: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/query-engine-rhel-openssl-1.0.x") Files in /: bin boot dev etc home lib lib64 media mnt opt proc root run sbin srv sys tmp usr var You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma-client-js/issues/new at PrismaClientFetcher.request (/var/task/pages/api/drafts.js:207:52429) at process._tickCallback (internal/process/next_tick.js:68:7)`

This happens because the binary isn't copied over into the Lambda. Looking at how [`serverless-next.js` works](https://github.com/danielcondemarin/serverless-next.js/blob/14fb4f6e57777bae15fbd29f4fa1a513191da30a/packages/lambda-at-edge/src/build.ts#L137), I thought I'd copy the binary directly into the `api` lambda deployment:

Here's my `next.config.js`:
```js
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');

module.exports = {
  target: 'serverless',

  webpack: (config, {}) => {
    config.plugins.push(new CopyWebpackPlugin([
      {
        from: path.join(__dirname, 'node_modules/@prisma/client/runtime/query-engine-rhel-openssl-1.0.x'),
        to: path.join(__dirname, '.next/serverless/pages/api/')
      }
    ]));

    return config;
  },
};
```

This works, and the lambda appears to have the binary there, but the problem is it's not discovering the path to it correrctly. Specifically, [`getPrismaPath()`](https://github.com/prisma/prisma/blob/cf0adc4ca43a72128b6927f935200aa5052c482d/src/packages/engine-core/src/NodeEngine.ts#L214) appears to be returning `/` on the Lambda.

How can I override this resolution path? `PRISMA_QUERY_ENGINE_BINARY` appears to be respected only for the actual build, not runtime. Will look into this further later, but wanted to post if anyone here has any suggestions. (cc @divyenduz @Jolg42 @danielcondemarin)

**Comment by vaskevich** [comment]
Alright, I spend some more time on this and pretty much got it working!

First off, it looks like the prisma resolution wasn't working due to [an issue](https://github.com/webpack/webpack/issues/1599) with `__dirname` that plagues webpack, so I had to modify the nuxt config.

Next, I ran into this:

```
ERROR	{ Error: 
Invalid 'prisma.post.findMany()' invocation:

EROFS: read-only file system, chmod '/var/task/pages/api/query-engine-rhel-openssl-1.0.x'
    at PrismaClientFetcher.request (/var/task/pages/api/drafts.js:206:52123)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'EROFS', meta: undefined }
```

and as it turns out, the query engine lost its executable flag. Actually, it lost it a couple times:
- Once due to `CopyWebpackPlugin` ([known issue](https://github.com/webpack-contrib/copy-webpack-plugin/issues/35)). The solution was to use `WebpackPermissionsPlugin`
- Again by the `aws-lambda` serverless component, internally used by `serverless-next.js` (also a [known issue](https://github.com/serverless-components/aws-lambda/issues/25)). There was a patch for that package, but unfortunately it wasn't as easy as using `patch-package`, as Serverless downloads components directly from NPM into a private registry cache in `~/.serverless`. So, I published a [patched package](https://www.npmjs.com/package/serverless-nextjs-lambda-binary-fix)

Here's the working `next.config.js`:

```js
const CopyWebpackPlugin = require("copy-webpack-plugin");
const WebpackPermissionsPlugin = require("webpack-permissions-plugin");
const path = require("path");

module.exports = {
  target: "serverless",

  webpack: (config, {}) => {
    config.plugins.push(
      new CopyWebpackPlugin([
        {
          from: path.join(
            __dirname,
            "node_modules/@prisma/client/runtime/query-engine-rhel-openssl-1.0.x"
          ),
          to: path.join(
            __dirname,
            ".next/serverless/pages/api/query-engine-rhel-openssl-1.0.x"
          ),
        },
        {
          from: path.join(__dirname, "prisma/schema.prisma"),
          to: path.join(__dirname, ".next/serverless/pages/api/"),
        },
      ])
    );
    config.plugins.push(
      new WebpackPermissionsPlugin({
        buildFiles: [
          {
            path: path.join(
              __dirname,
              ".next/serverless/pages/api/query-engine-rhel-openssl-1.0.x"
            ),
            fileMode: "755",
          },
        ],
      })
    );

    // https://github.com/webpack/webpack/issues/1599
    config.node.__dirname = false;

    return config;
  },
};
```

And then `serverless.yml` becomes:
```yml
example:
    component: serverless-nextjs-lambda-binary-fix@1.11.4
```

I ran into issues with the backend not being able to read the SQLite database, but that would be swapped for an actual DB anyway. :)

It would be awesome if all these issues got patched up in their respective projects, as I'd expect such a prominent example to work reasonably well without a day's worth of debugging!

**Comment by pantharshit00** [comment]
Thanks for the write up! This has been reported a couple of times before in related issues: https://github.com/prisma/prisma/issues/2303

**Comment by vaskevich** [comment]
Ah, didn't come across that issue in my search. :) Cool! Looks like the solution there is slightly different since it's not specific to next.js and its Serverless component.
