### ISSUE TITLE
Argument not for where.OR.1.codes.some.code.not must not be null. Please use undefined instead.

### ISSUE THREAD

**Issue by adrianoresende** [prisma/prisma-client-js#706]
## Bug description

The query was working correctly **until** I modified a model but the attribute `codes` had no changes and neither the relationship with type `code`

### Before:
```
model Component {
  id           Int @id @default(autoincrement())
  title        String
  premium      Boolean
  codes        Code[]
  images       ComponentImage[]
  group        ComponentGroup @relation(fields: [groupId], references: [id])
  groupId      Int
  published    Boolean
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
```
### After
```
model Component {
  id           Int @id @default(autoincrement())
  title        String
  premium      Boolean
  codes        Code[]
  imageMobile  String?
  imageTablet  String?
  imageDesktop String?
  group        ComponentGroup @relation(fields: [groupId], references: [id])
  groupId      Int
  published    Boolean
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
```

I had a problem with the command `migrate up`, so I:
- truncated _Migration
- removed the Migration folder
- deleted the ComponentImage table

and after worked fine.

When I ran a query and I got an error:
```
{
  "errors": [
    {
      "message": "\nInvalid `prisma.component.findMany()` invocation in\n/Users/adriano/Documents/Codes/lib/graphql-prisma/src/resolvers/Query.js:34:29\n\n  30     },\n  31   }\n  32 }\n  33 \n→ 34 return prisma.component.findMany({\n       where: {\n         group: {\n           slug: undefined,\n           category: {\n             type: undefined\n           }\n         },\n         published: true,\n         OR: [\n           {\n             imageDesktop: {\n               not: null\n             }\n           },\n           {\n             codes: {\n               some: {\n                 code: {\n                   not: null\n                        ~~~~\n                 }\n               }\n             }\n           }\n         ]\n       },\n       include: {\n         group: {\n           include: {\n             category: true\n           }\n         },\n         codes: true\n       }\n     })\n\nArgument not for where.OR.1.codes.some.code.not must not be null. Please use undefined instead.\n\n",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "components"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: ",
            "Invalid `prisma.component.findMany()` invocation in",
            "/Users/adriano/Documents/Codes/lib/graphql-prisma/src/resolvers/Query.js:34:29",
            "",
            "  30     },",
            "  31   }",
            "  32 }",
            "  33 ",
            "→ 34 return prisma.component.findMany({",
            "       where: {",
            "         group: {",
            "           slug: undefined,",
            "           category: {",
            "             type: undefined",
            "           }",
            "         },",
            "         published: true,",
            "         OR: [",
            "           {",
            "             imageDesktop: {",
            "               not: null",
            "             }",
            "           },",
            "           {",
            "             codes: {",
            "               some: {",
            "                 code: {",
            "                   not: null",
            "                        ~~~~",
            "                 }",
            "               }",
            "             }",
            "           }",
            "         ]",
            "       },",
            "       include: {",
            "         group: {",
            "           include: {",
            "             category: true",
            "           }",
            "         },",
            "         codes: true",
            "       }",
            "     })",
            "",
            "Argument not for where.OR.1.codes.some.code.not must not be null. Please use undefined instead.",
            "",
            "",
            "    at Document.validate (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/@prisma/client/src/runtime/query.ts:256:19)",
            "    at Object.model [as Component] (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:435:20)",
            "    at Object.findMany (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:553:33)",
            "    at components (/Users/adriano/Documents/Codes/lib/graphql-prisma/src/resolvers/Query.js:34:29)",
            "    at field.resolve (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at resolveFieldValueOrError (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql/execution/execute.js:486:18)",
            "    at resolveField (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql/execution/execute.js:444:16)",
            "    at executeFields (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql/execution/execute.js:281:18)",
            "    at executeOperation (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql/execution/execute.js:225:122)",
            "    at executeImpl (/Users/adriano/Documents/Codes/lib/graphql-prisma/node_modules/graphql/execution/execute.js:102:14)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

I tested with `undefined` but some item return with `codes: []` and `imageDesktop: null`

If I comment this lines in Query (below):
```
codes: {
  some: {
    code: { not: null }
  }
}
```
The error disappears

## Expected behavior

Return without codes empty as before.

## Prisma information

Query:
### Before
```
components(parent, args, { prisma, request }) {
  let whereArgs = {}

  if (args.where) {
    whereArgs = {
      group: {
        slug: args.where.slug,
        category: {
          type: args.where.type
        }
      },
    }
  }

  return prisma.component.findMany({
    where: {
      ...whereArgs,
      published: true,
      OR: [
        {
          images: {
            some: {
              desktopSrc: { not: null }
            }
          }
        },
        {
          codes: {
            some: {
              code: { not: null }
            }
          }
        }
      ]
    },
    include: {
      group: {
        include: {
          category: true
        }
      },
      codes: true,
      images: true
    }
  })
},
```

### After
```
components(parent, args, { prisma, request }) {
  let whereArgs = {}

  if (args.where) {
    whereArgs = {
      group: {
        slug: args.where.slug,
        category: {
          type: args.where.type
        }
      },
    }
  }

  return prisma.component.findMany({
    where: {
      ...whereArgs,
      published: true,
      OR: [
        {
          imageDesktop: { not: null }
        },
        {
          codes: {
            some: {
              code: { not: null }
            }
          }
        }
      ]
    },
    include: {
      group: {
        include: {
          category: true
        }
      },
      codes: true,
    }
  })
},
```

## Environment & setup

- OS: macOS 10.15.4
- Database: PostgreSQL
- Prisma version: 2.0.0-alpha.1257
- Node.js version: v13.3.0

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `alpha.1299`:
![image](https://user-images.githubusercontent.com/22195362/83826541-c7f4d400-a6f9-11ea-8ad5-42f2d93c61b0.png)


Can you please try this again with the latest alpha?

**Comment by adrianoresende** [comment]
Today I updated to v2.2.0 and the error persist.

The error disappears when I comment or removing `code: { not: null }`

**Comment by pantharshit00** [comment]
@adrianoresende Can you share a SQL dump of your database so that I can import it? You can either upload it here or send it to "schemas@prisma.io" if the data is sensitive. 

We can also sign a NDA if you want.

**Comment by janpio** [comment]
Ping @adrianoresende about Harshit's last followup.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please open a new issue in https://github.com/prisma/prisma if you want us to take another look.
