### ISSUE TITLE
Unknown error in Prisma Client

### ISSUE THREAD

**Issue by hcmuleva** [prisma/prisma-client-js#724]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v14.3.0            | 
| OS       | darwin             |
| Prisma   | 2.0.0              |

## Logs
```
;214m+6ms
  prisma-client Generated request:  +6ms
  prisma-client mutation {
  prisma-client   createOneUser(data: {
  prisma-client     user_first_name: "st"
  prisma-client     user_last_name: "co1"
  prisma-client     user_name: "st1"
  prisma-client     user_email: "stt@co1.com"
  prisma-client     user_gender: Female
  prisma-client     user_biography: "Test account"
  prisma-client     user_mobile: 0
  prisma-client     user_avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/dimaposnyy/128.jpg"
  prisma-client     user_time_zone: "2020-05-17T13:25:25.858Z"
  prisma-client     user_password: "..."
  prisma-client     user_birthday: "2020-05-17T13:25:25.858Z"
  prisma-client     user_language: English
  prisma-client     user_email_verified: true
  prisma-client     Organization: {
  prisma-client       connect: {
  prisma-client         organization_id: 53
  prisma-client       }
  prisma-client     }
  prisma-client     Assigned_Role: {
  prisma-client       create: [
  prisma-client         {
  prisma-client           Organization: {
  prisma-client             connect: {
  prisma-client               organization_id: 53
  prisma-client             }
  prisma-client           }
  prisma-client           Sub_Organization: {
  prisma-client             connect: {
  prisma-client               sub_organization_id: 51
  prisma-client             }
  prisma-client           }
  prisma-client           Group: {
  prisma-client             connect: {
  prisma-client               group_id: 55
  prisma-client             }
  prisma-client           }
  prisma-client           Sub_Group: {
  prisma-client             connect: {
  prisma-client               sub_group_id: 51
  prisma-client             }
  prisma-client           }
  prisma-client           user_role: Parent
  prisma-client         }
  prisma-client       ]
  prisma-client     }
  prisma-client   }) {
  prisma-client     organization_id
  prisma-client     user_active_status
  prisma-client     user_avatar
  prisma-client     user_biography
  prisma-client     user_birthday
  prisma-client     user_created_at
  prisma-client     user_email
  prisma-client     user_email_verified
  prisma-client     user_first_name
  prisma-client     user_gender
  prisma-client     user_id
  prisma-client     user_language
  prisma-client     user_last_name
  prisma-client     user_mobile
  prisma-client     user_mobile_verified
  prisma-client     user_name
  prisma-client     user_password
  prisma-client     user_time_zone
  prisma-client     user_updated_at
  prisma-client   }
  prisma-client }
  prisma-client   +5ms
  printStack callsite  Error: 
    at Object.model [as User] (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:498:46)
    at Object.create (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:626:33)
    at _callee4$ (/Users/myproj/tests/users/bulkuser.test.js:102:44)
    at tryCatch (/Users/myproj/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)  +508ms
  printStack callsite  Error: 
    at Object.model [as User] (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:498:46)
    at Object.create (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:626:33)
    at _callee4$ (/Users/myproj/tests/users/bulkuser.test.js:102:44)
    at tryCatch (/Users/myproj/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)  +11ms
  printStack callsite  Error: 
    at Object.model [as User] (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:498:46)
    at Object.create (/Users/myproj/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:626:33)
    at _callee4$ (/Users/myproj/tests/users/bulkuser.test.js:102:44)
    at tryCatch (/Users/myproj/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/myproj/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/myproj/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)  +18ms
```

**Comment by pantharshit00** [comment]
Hi @hcmuleva 

Can you please provide a reproduction from this? This provided information is insufficient for us to triage this.

**Comment by hcmuleva** [comment]
Issue related to date. So I am able to progress now. Thanks
