### ISSUE TITLE
Unknown error in Prisma Client

### ISSUE THREAD

**Issue by hjkang-danbi** [prisma/prisma-client-js#754]
I got some error like below at prisma.<someModel>.create
there was no clue without it so I didn't know what's the problem and what should I do.

## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v14.3.0            | 
| OS       | darwin             |
| Prisma   | 2.0.1              |

## Logs
```
2:cc:62:3a:ab'
  prisma-client   }
  prisma-client })  +0ms
  prisma-client Generated request:  +0ms
  prisma-client mutation {
  prisma-client   createOneRawUser(data: {
  prisma-client     lang: "ko-kr"
  prisma-client     os: "mos"
  prisma-client     agent: "chrome"
  prisma-client     userMac: "d1:52:62:18:78:f3"
  prisma-client     accessType: CONNECT
  prisma-client     createdAt: "2020-06-25T17:08:06.583Z"
  prisma-client     updatedAt: "2020-06-25T17:08:06.583Z"
  prisma-client     adRawUser: {
  prisma-client       create: {
  prisma-client         createdAt: "2020-06-25T17:08:06.583Z"
  prisma-client         updatedAt: "2020-06-25T17:08:06.583Z"
  prisma-client         charge: 0
  prisma-client         advertisement: {
  prisma-client           connect: {
  prisma-client             id: 1
  prisma-client           }
  prisma-client         }
  prisma-client       }
  prisma-client     }
  prisma-client     storeBy: {
  prisma-client       connect: {
  prisma-client         id: 1
  prisma-client       }
  prisma-client     }
  prisma-client     routerMac: "84:a2:cc:62:3a:ab"
  prisma-client   }) {
  prisma-client     id
  prisma-client     createdAt
  prisma-client     updatedAt
  prisma-client     accessType
  prisma-client     lang
  prisma-client     os
  prisma-client     agent
  prisma-client     userMac
  prisma-client     routerMac
  prisma-client     storeById
  prisma-client   }
  prisma-client }
  prisma-client   +0ms
  prisma-client Prisma Client call:  +1ms
  prisma-client prisma.rawUser.create({
  prisma-client   data: {
  prisma-client     lang: 'ko-kr',
  prisma-client     os: 'mos',
  prisma-client     agent: 'chrome',
  prisma-client     userMac: 'fb:7a:57:9b:d1:92',
  prisma-client     accessType: 'CONNECT',
  prisma-client     createdAt: new Date('2020-06-25T17:08:06.583Z'),
  prisma-client     updatedAt: new Date('2020-06-25T17:08:06.583Z'),
  prisma-client     adRawUser: {
  prisma-client       create: {
  prisma-client         createdAt: new Date('2020-06-25T17:08:06.583Z'),
  prisma-client         updatedAt: new Date('2020-06-25T17:08:06.583Z'),
  prisma-client         charge: 0,
  prisma-client         advertisement: {
  prisma-client           connect: {
  prisma-client             id: 1
  prisma-client           }
  prisma-client         }
  prisma-client       }
  prisma-client     },
  prisma-client     storeBy: {
  prisma-client       connect: {
  prisma-client         id: 1
  prisma-client       }
  prisma-client     },
  prisma-client     routerMac: '1f:ac:2d:21:4b:75'
  prisma-client   }
  prisma-client })  +1ms
  prisma-client Generated request:  +0ms
  prisma-client mutation {
  prisma-client   createOneRawUser(data: {
  prisma-client     lang: "ko-kr"
  prisma-client     os: "mos"
  prisma-client     agent: "chrome"
  prisma-client     userMac: "fb:7a:57:9b:d1:92"
  prisma-client     accessType: CONNECT
  prisma-client     createdAt: "2020-06-25T17:08:06.583Z"
  prisma-client     updatedAt: "2020-06-25T17:08:06.583Z"
  prisma-client     adRawUser: {
  prisma-client       create: {
  prisma-client         createdAt: "2020-06-25T17:08:06.583Z"
  prisma-client         updatedAt: "2020-06-25T17:08:06.583Z"
  prisma-client         charge: 0
  prisma-client         advertisement: {
  prisma-client           connect: {
  prisma-client             id: 1
  prisma-client           }
  prisma-client         }
  prisma-client       }
  prisma-client     }
  prisma-client     storeBy: {
  prisma-client       connect: {
  prisma-client         id: 1
  prisma-client       }
  prisma-client     }
  prisma-client     routerMac: "1f:ac:2d:21:4b:75"
  prisma-client   }) {
  prisma-client     id
  prisma-client     createdAt
  prisma-client     updatedAt
  prisma-client     accessType
  prisma-client     lang
  prisma-client     os
  prisma-client     agent
  prisma-client     userMac
  prisma-client     routerMac
  prisma-client     storeById
  prisma-client   }
  prisma-client }
  prisma-client   +0ms
  printStack callsite  Error: 
    at Object.model [as RawUser] (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:498:46)
    at Object.n.<computed> [as create] (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:626:33)
    at Object.<anonymous> (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/prisma/seed/generator/RawUser.ts:52:26)
    at step (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/prisma/seed/generator/RawUser.ts:33:23)
    at Object.next (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/prisma/seed/generator/RawUser.ts:14:53)
    at fulfilled (/Users/hj.kang/Documents/GitProject/ad-fi-16-prisma2-nexus/prisma/seed/generator/RawUser.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)  +957ms
```

**Comment by pantharshit00** [comment]
@hjkang-danbi Can you please provide a minimal reproduction for this? I can't replicate the issue with the current details here.

A reproduction should ideally contain you model and some code that can be used to reproduce the problem.

**Comment by timsuchanek** [comment]
Closing this due to inactivity.
