### ISSUE TITLE
Enum value 'false' breaks Prisma client create

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-client-js#776]
## Bug description

If an enum has 'false' as one of the possible values. Prisma client fails at runtime while providing 'false' as the value for that enum. 

## How to reproduce

1. Run the following SQL in a MySQL (untested with Postgres, SQLite) database 

```
CREATE TABLE `e` (
  `id` bigint(20) unsigned NOT NULL,
  `visible` enum('true','false') NOT NULL DEFAULT 'true',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

2. Introspect and generate client

```
model e {
  id      Int       @id
  visible e_visible @default(true)
}

enum e_visible {
  true
  false
}
```

3. Run the following Prisma client code

```
const data = await prisma.e.create({
    data: {
      id: 1,
      visible: 'false',
    },
})
```

4. It fails with

```
divyendusingh [p2-enum-bool]$ node index.js                                                                                                 130 ↵
(node:21526) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.e.create()` invocation in
/Users/divyendusingh/Documents/prisma/p2-enum-bool/index.js:6:31

  2
  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   const data = await prisma.e.create(
  Failed to validate the query `Error occurred during query validation & transformation:
Mutation (object)
  ↳ createOnee (field)
    ↳ data (argument)
      ↳ eCreateInput (object)
        ↳ visible (field)
          ↳ Error parsing value: Enum value 'false ' is invalid for enum type e_visible.` at `.Mutation.createOnee.data.eCreateInput.visible`
    at PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/client/runtime/index.js:1:206978)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Expected behavior

It should work

## Prisma information

```
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/.bin/prisma --version
@prisma/cli          : 2.3.0-dev.16
Current platform     : darwin
Query Engine         : query-engine 21bd701db858e37b8f3157190a86da93e21ec5df (at /Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 21bd701db858e37b8f3157190a86da93e21ec5df (at /Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 21bd701db858e37b8f3157190a86da93e21ec5df (at /Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 21bd701db858e37b8f3157190a86da93e21ec5df (at /Users/divyendusingh/Documents/prisma/p2-enum-bool/node_modules/@prisma/cli/prisma-fmt-darwin)
Done in 1.42s.
```

Test utils database affected: 

- mysql/piwigo

**Comment by pantharshit00** [comment]
I can reproduce this:
![image](https://user-images.githubusercontent.com/22195362/87415117-51959c80-c5ea-11ea-8c76-81a59ef4cfdc.png)
Version used: `2.3.0-dev.20`

**Comment by dpetrick** [comment]
Please confirm that the latest dev (2.2.1-dev.4 onwards) fixes this issue. Note: At the time of writing, the client publishing fails, so you need to check at some point when the snapshot tests are fixed.

**Comment by pantharshit00** [comment]
I can confirm this has been fixed. I tested with `2.3.0-dev.55`
