### ISSUE TITLE
Unknown error in Prisma Client

### ISSUE THREAD

**Issue by hayes** [prisma/prisma-client-js#787]
The link in the original error was too big, it looks like the log recursively includes another error (with link to github template).  I did my best to mimic the original intent of the crash report link by manually extracting the url parameters and formatting them into this issue. 

Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.16.3           |
| OS       | rhel-openssl-1.0.x |
| Prisma   | 2.2.2              |

## Logs
```
eferral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+0%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A04%3A49.972Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A04%3A49.972Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+0%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A06.740Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A06.740Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+16%2C%0A++skip%3A+10%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A06.740Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A06.740Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+16%0A++++skip%3A+10%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A11.666Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A11.666Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+6%2C%0A++skip%3A+25%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A11.666Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A11.666Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+6%0A++++skip%3A+25%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A12.646Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A12.646Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+30%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A12.646Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A12.646Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+30%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A36.263Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A36.263Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+0%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A36.263Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A36.263Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+0%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A40.962Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A40.962Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+0%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A40.962Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A40.962Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+0%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A43.372Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A43.372Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+10%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A43.372Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A43.372Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+10%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A05%3A44.303Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A05%3A44.303Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+20%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A05%3A44.303Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A05%3A44.303Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+20%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A2020-07-18T00%3A14%3A53.338Z+prisma-client+Prisma+Client+call%3A%0A2020-07-18T00%3A14%3A53.339Z+prisma-client+prisma.referral_codes.findMany%28%7B%0A++take%3A+11%2C%0A++skip%3A+0%2C%0A++orderBy%3A+%7B%0A++++id%3A+%27desc%27%0A++%7D%0A%7D%29%0A2020-07-18T00%3A14%3A53.339Z+prisma-client+Generated+request%3A%0A2020-07-18T00%3A14%3A53.339Z+prisma-client+query+%7B%0A++findManyreferral_codes%28%0A++++take%3A+11%0A++++skip%3A+0%0A++++orderBy%3A+id_DESC%0A++%29+%7B%0A++++code%0A++++id%0A++++name%0A++%7D%0A%7D%0A%0A%60%60%60%0A&title=Unknown+error+in+Prisma+Client&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at NodeEngine.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:1:114482)
    at async PrismaClientFetcher._request (/var/task/node_modules/@prisma/client/runtime/index.js:1:206476)
    at async resolveOffsetConnection (/var/task/node_modules/@giraphql/plugin-relay/lib/utils/connections.js:76:17)
    at async wrappedResolver (/var/task/node_modules/@giraphql/core/lib/plugins/wrap-field.js:52:142)
2020-07-18T00:16:12.516Z prisma-client Prisma Client call:
2020-07-18T00:16:12.516Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:16:12.516Z prisma-client Generated request:
2020-07-18T00:16:12.516Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

2020-07-18T00:16:27.204Z prisma-client Prisma Client call:
2020-07-18T00:16:27.204Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:16:27.204Z prisma-client Generated request:
2020-07-18T00:16:27.204Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

2020-07-18T00:16:35.306Z prisma-client Prisma Client call:
2020-07-18T00:16:35.306Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:16:35.306Z prisma-client Generated request:
2020-07-18T00:16:35.306Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

2020-07-18T00:16:36.790Z prisma-client Prisma Client call:
2020-07-18T00:16:36.791Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:16:36.791Z prisma-client Generated request:
2020-07-18T00:16:36.791Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

2020-07-18T00:16:39.632Z prisma-client Prisma Client call:
2020-07-18T00:16:39.632Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:16:39.632Z prisma-client Generated request:
2020-07-18T00:16:39.632Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

2020-07-18T00:18:37.694Z prisma-client Prisma Client call:
2020-07-18T00:18:37.694Z prisma-client prisma.referral_codes.findMany({
  take: 11,
  skip: 0,
  orderBy: {
    id: 'desc'
  }
})
2020-07-18T00:18:37.694Z prisma-client Generated request:
2020-07-18T00:18:37.694Z prisma-client query {
  findManyreferral_codes(
    take: 11
    skip: 0
    orderBy: id_DESC
  ) {
    code
    id
    name
  }
}

```

## Bug description

Primsa crashses/errors out on a fairly simple query.  This happens inconsistently, and I have replayed the same request in chrome dev tools that failed and it succeeded the second time.

## How to reproduce

I have not found a way to reliably reproduce the error, but the few times I have seen it happen it seems to be the first time I've touched the page in a while, so I wonder if it could be caused by a stale/broken connection or something

## Expected behavior

Query should succeed

## Prisma information

the model for the relevant table is, the full schema has 50+ tables (from introspection) so I didn't want to include the full schema.

```
model referral_codes {
  code           String?          @unique
  id             Int              @default(autoincrement()) @id
  name           String           @unique
  user_referrals user_referrals[]
}
```

The query is:
```ts
prisma.referral_codes.findMany({
  take: limit,
  skip: offset,
  orderBy: {
    id: 'desc',
  },
});
``` 

`limit` and `offset` have been 11 and 0 consistently when this error has occured, and the table has about 130 rows

## Environment & setup
Serverless on s3, more details on os in the crash report above.

**Comment by hayes** [comment]
The begging of the log is not a typo, that's what was included in the crash report URL.

**Comment by alexvilchis** [comment]
Happens to me too. https://github.com/prisma/prisma-client-js/issues/789

**Comment by hayes** [comment]
closing as a duplicate of #789
