### ISSUE TITLE
Interval data type

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma-client-js#813]
I am busy switching from sequelize to prisma. Most of it works, but there's a custom data type of `interval` that we've been using in sequelize. We use [this](https://github.com/abelosorio/sequelize-interval-postgres#readme) package.

When I ran `prisma instrospect` it generated type `String?` which is obviously wrong. 

I get a pretty useless error message when I run into this. 

```sh
 Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(7), cause: Some(WrongType { postgres: Interval, rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1223:15)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

My model has over 100 fields on it and I had to figure out which field was causing it by process of elimination. 

Reading the error message again after figuring the issue out I saw "Interval" was in there, but it was not clear that it's a data type of Interval causing it, nor did it say which field in my selection was causing it. I'd suggest some better error message in general when a specific selection fails. 

I'd also like to request that Prisma can handle [Interval data types for postgres](https://www.postgresql.org/docs/9.2/datatype-datetime.html#DATATYPE-INTERVAL-INPUT)

**Comment by janpio** [comment]
Can you quickly open a new issue for the "Support interval data type for Postgres"? Then we can use this one here to improve the error message (which we totally want to do of course - that should be much easier for you to figure out!

Also, if `String` is not the right thing to use for `interval`, we might also want to consider this a bug in Introspection and fix it. Can you maybe share a minimal schema that shows exactly the problem you are getting (so SQL schema + Prisma schema + query you are trying to run). That will allow us to reproduce, decide if it is a bug and then fix.

**Comment by mspix** [comment]
I get the same error message, because of a relation using the interval type for one column.
The relation has its column declared like this:

`"timezoneOffset" INTERVAL NOT NULL DEFAULT '0 hours 0 min 0 sec'`

The error message gets triggered as soon as I execute

```
const relation = await prisma.relation
    .findOne({
      where: {
        id,
      },
    })
```

Afterwards I found out at this page
[type-mapping-between-postgresql-to-prisma-schema](https://www.prisma.io/docs/reference/database-connectors/postgresql#type-mapping-between-postgresql-to-prisma-schema)
that interval is not supported yet.

I hope the support of this type is coming soon 😅

**Comment by cyrus-za** [comment]
@janpio here's the issue as requested: https://github.com/prisma/prisma-client-js/issues/917

I'll rename this one to match the error handling

**Comment by cyrus-za** [comment]
@mspix be sure to give that issue a thumbs up so the prisma team can prioritise it

**Comment by kevinfaguiar-tc** [comment]
@janpio Should this error be happening in every query that selects a INTERVAL type field? 
I mean, the scenario here is that introspection works but when querying a table using the introspected Prisma client it crashes... Why?

**Comment by janpio** [comment]
Interval types are not supported at all (see https://github.com/prisma/prisma-client-js/issues/917 for a request to fix that), so whatever is introspected or any queries run against these fields have undefined and probably broken behavior.
