### ISSUE TITLE
Started http server

### ISSUE THREAD

**Issue by Kalinkin92** [prisma/prisma-client-js#825]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v10.16.3           | 
| OS       | rhel-openssl-1.0.x |
| Prisma   | 2.1.3              |

# Description
```
Started http server
```

## Logs
```
nt+++++rentFinishedAt%0A++prisma-client+++%7D%0A++prisma-client+%7D%0A++prisma-client+++%2B0ms%0A++plusX+Execution+permissions+of+%2Fvar%2Fwww%2Fup-osmp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-rhel-openssl-1.0.x+are+fine++%2B481ms%0A++prisma-client+Client+Version+2.1.3++%2B140ms%0A++prisma-client+Engine+Version+e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e++%2B0ms%0A%60%60%60%0A&title=Started+http+server&template=bug_report.md
  prisma-client 
  prisma-client If you want the Prisma team to look into it, please open the link above 🙏
  prisma-client 
  prisma-client     at NodeEngine.handleRequestError (/var/www/up-osmp/node_modules/@prisma/engine-core/dist/NodeEngine.js:151:1)
  prisma-client     at process._tickCallback (internal/process/next_tick.js:68:7)  +10ms
  prisma-client Prisma Client call:  +42ms
  prisma-client prisma.objects.findMany({
  prisma-client   orderBy: {
  prisma-client     created_at: 'desc'
  prisma-client   },
  prisma-client   where: {
  prisma-client     is_on_map: true
  prisma-client   },
  prisma-client   include: {
  prisma-client     access_products: {
  prisma-client       select: {
  prisma-client         rentFinishedAt: true
  prisma-client       },
  prisma-client       orderBy: {
  prisma-client         createdAt: 'desc'
  prisma-client       },
  prisma-client       where: {
  prisma-client         accessType: 'LONG',
  prisma-client         rentFinishedAt: {
  prisma-client           gt: new Date('2020-08-11T00:07:18.916Z')
  prisma-client         },
  prisma-client         users: {
  prisma-client           id: undefined
  prisma-client         }
  prisma-client       }
  prisma-client     },
  prisma-client     controllers: {
  prisma-client       where: {
  prisma-client         in: true
  prisma-client       }
  prisma-client     },
  prisma-client     pictures: true,
  prisma-client     reviews: true
  prisma-client   }
  prisma-client })  +1ms
  prisma-client Generated request:  +0ms
  prisma-client query {
  prisma-client   findManyobjects(
  prisma-client     orderBy: created_at_DESC
  prisma-client     where: {
  prisma-client       is_on_map: true
  prisma-client     }
  prisma-client   ) {
  prisma-client     id
  prisma-client     address_obj
  prisma-client     country
  prisma-client     city
  prisma-client     street
  prisma-client     places_count
  prisma-client     desc_obj
  prisma-client     roof_type
  prisma-client     is_secure
  prisma-client     is_video_on
  prisma-client     is_warm
  prisma-client     height
  prisma-client     pricing_obj
  prisma-client     price_hour
  prisma-client     price_day
  prisma-client     price_month
  prisma-client     rating
  prisma-client     created_at
  prisma-client     updated_at
  prisma-client     lat
  prisma-client     lng
  prisma-client     manager_id
  prisma-client     is_short_rent
  prisma-client     is_long_rent
  prisma-client     is_open_by_ble
  prisma-client     is_in
  prisma-client     icon_jsonb
  prisma-client     icon
  prisma-client     images
  prisma-client     title
  prisma-client     is_on_map
  prisma-client     images_json
  prisma-client     access_products(
  prisma-client       orderBy: createdAt_DESC
  prisma-client       where: {
  prisma-client         accessType: LONG
  prisma-client         rentFinishedAt_gt: "2020-08-11T00:07:18.916Z"
  prisma-client         users: {
  prisma-client 
  prisma-client         }
  prisma-client       }
  prisma-client     ) {
  prisma-client       rentFinishedAt
  prisma-client     }
  prisma-client     controllers(where: {
  prisma-client       in: true
  prisma-client     }) {
  prisma-client       id
  prisma-client       data
  prisma-client       object_id
  prisma-client       createdat
  prisma-client       updatedat
  prisma-client       name
  prisma-client       secret
  prisma-client       in
  prisma-client       out
  prisma-client     }
  prisma-client     pictures {
  prisma-client       id
  prisma-client       url
  prisma-client       name
  prisma-client       object_id
  prisma-client       createdat
  prisma-client       updatedat
  prisma-client     }
  prisma-client     reviews {
  prisma-client       id
  prisma-client       user_id
  prisma-client       object_id
  prisma-client       rent_id
  prisma-client       message
  prisma-client       rate
  prisma-client       createdAt
  prisma-client       updatedAt
  prisma-client     }
  prisma-client   }
  prisma-client }
  prisma-client   +0ms
  plusX Execution permissions of /var/www/up-osmp/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine  +188ms
  prisma-client Client Version 2.1.3  +91ms
  prisma-client Engine Version e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e  +0ms
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by timsuchanek** [comment]
Closing due to inactivity
