### ISSUE TITLE
Started http server

### ISSUE THREAD

**Issue by jmcmullen** [prisma/prisma-client-js#826]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.18.2           | 
| OS       | rhel-openssl-1.0.x |
| Prisma   | 2.3.0              |

# Description
```
Started http server
```

## Logs
```
2020-08-11T05:32:48.863Z prisma-client {
  engineConfig: {
    cwd: '/var/task/src/node_modules/.prisma/client',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/var/task/src/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/opt/build/repo/node_modules/@prisma/client',
      binaryTargets: [Array],
      previewFeatures: [Array],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.3.0',
    enableExperimental: [ 'aggregations' ]
  }
}
2020-08-11T05:32:50.250Z plusX Execution permissions of /var/task/src/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
2020-08-11T05:32:50.491Z prisma-client Client Version 2.3.0
2020-08-11T05:32:50.491Z prisma-client Engine Version e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e
2020-08-11T05:35:50.930Z prisma-client Error: Started http server

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name+++++%7C+Version++++++++++++%7C%0A%7C----------%7C--------------------%7C%0A%7C+Node+++++%7C+v12.18.2+++++++++++%7C+%0A%7C+OS+++++++%7C+rhel-openssl-1.0.x+%7C%0A%7C+Prisma+++%7C+2.3.0++++++++++++++%7C%0A%0A%23+Description%0A%60%60%60%0AStarted+http+server%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0A2020-08-11T05%3A32%3A48.863Z+prisma-client+%7B%0A++engineConfig%3A+%7B%0A++++cwd%3A+%27%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%27%2C%0A++++enableDebugLogs%3A+false%2C%0A++++enableEngineDebugMode%3A+undefined%2C%0A++++datamodelPath%3A+%27%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%2Fschema.prisma%27%2C%0A++++prismaPath%3A+undefined%2C%0A++++engineEndpoint%3A+undefined%2C%0A++++generator%3A+%7B%0A++++++name%3A+%27client%27%2C%0A++++++provider%3A+%27prisma-client-js%27%2C%0A++++++output%3A+%27%2Fopt%2Fbuild%2Frepo%2Fnode_modules%2F%40prisma%2Fclient%27%2C%0A++++++binaryTargets%3A+%5BArray%5D%2C%0A++++++previewFeatures%3A+%5BArray%5D%2C%0A++++++config%3A+%7B%7D%0A++++%7D%2C%0A++++showColors%3A+false%2C%0A++++logLevel%3A+undefined%2C%0A++++logQueries%3A+undefined%2C%0A++++flags%3A+%5B%5D%2C%0A++++clientVersion%3A+%272.3.0%27%2C%0A++++enableExperimental%3A+%5B+%27aggregations%27+%5D%0A++%7D%0A%7D%0A2020-08-11T05%3A32%3A50.250Z+plusX+Execution+permissions+of+%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-rhel-openssl-1.0.x+are+fine%0A2020-08-11T05%3A32%3A50.491Z+prisma-client+Client+Version+2.3.0%0A2020-08-11T05%3A32%3A50.491Z+prisma-client+Engine+Version+e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e%0A%60%60%60&title=Started+http+server&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at NodeEngine.handleRequestError (/var/task/src/node_modules/@prisma/client/runtime/index.js:1:115776)
    at async PrismaClientFetcher.request (/var/task/src/node_modules/@prisma/client/runtime/index.js:1:208913)
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?
