### ISSUE TITLE
Prisma server crashes while saving array(text) in Postgres.

### ISSUE THREAD

**Issue by rootandleaves** [prisma/prisma-client-js#906]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v13.8.0            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.8.0              |

# Description
```
signalCode: null | exitCode: 255 | killed: true
SocketError: closed
    at Socket.mc (/home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/@prisma/node_modules/.pnpm/undici@2.0.5/node_modules/undici/lib/core/client.js:687:31)
    at Socket.emit (events.js:321:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at TCP.<anonymous> (net.js:668:12)
Exit code: 255
Started http server
```

## Logs
```
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +14s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +1s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +2s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +1s
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by rootandleaves** [comment]
Suppose in Postgres you create table as follows:

| id  | createdAt  | updatedAt  | mobiles  |
|-----|---------------|----------------|-------------|
| 1  | 2:00BLABLA  | 2:00BLABLA  | +91992999999 |

#Schema
`
  id              String            @id @default(cuid())
  createdAt       DateTime          @default(now())
  updatedAt       DateTime          @default(now()) @updatedAt
  mobilenumber String               <------------ Just Change String to String[] as in postgres you could save list.
}
`

```
await Prisma.account({
  mobilenumber: [8826668515]
})
```

# Server will crash now for sure.

**Comment by pantharshit00** [comment]
@rootandleaves Sorry for the late reply here.  I am unable to reproduce this after using the correct types:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/22195362/103446056-4706b680-4ca1-11eb-91e6-5313912d8d2d.png">


If you looking to store BigInts instead of Strings, that is now possible with the new native types feature flag, check it out here: https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#bigint
