### ISSUE TITLE
PANIC: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by tijsproost** [prisma/prisma-client-js#919]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.0.1            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.9.0              |

## Logs
```
prisma-client {
  engineConfig: {
    cwd: '/usr/src/app',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/usr/src/app/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/usr/src/app/node_modules/@prisma/client',
      binaryTargets: [],
      previewFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: true,
    flags: [],
    clientVersion: '2.9.0',
    enableExperimental: [],
    useUds: undefined
  }
}
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma-client Error: PANIC: index out of bounds: the len is 1 but the index is 1

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v15.0.1++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+2.9.0++++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma-client+%7B%0A++engineConfig%3A+%7B%0A++++cwd%3A+%27%2Fusr%2Fsrc%2Fapp%27%2C%0A++++enableDebugLogs%3A+false%2C%0A++++enableEngineDebugMode%3A+undefined%2C%0A++++datamodelPath%3A+%27%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fschema.prisma%27%2C%0A++++prismaPath%3A+undefined%2C%0A++++engineEndpoint%3A+undefined%2C%0A++++generator%3A+%7B%0A++++++name%3A+%27client%27%2C%0A++++++provider%3A+%27prisma-client-js%27%2C%0A++++++output%3A+%27%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%27%2C%0A++++++binaryTargets%3A+%5B%5D%2C%0A++++++previewFeatures%3A+%5B%5D%2C%0A++++++config%3A+%7B%7D%0A++++%7D%2C%0A++++showColors%3A+false%2C%0A++++logLevel%3A+undefined%2C%0A++++logQueries%3A+true%2C%0A++++flags%3A+%5B%5D%2C%0A++++clientVersion%3A+%272.9.0%27%2C%0A++++enableExperimental%3A+%5B%5D%2C%0A++++useUds%3A+undefined%0A++%7D%0A%7D%0AplusX+Execution+permissions+of+%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0AplusX+Execution+permissions+of+%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0AplusX+Execution+permissions+of+%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0AplusX+Execution+permissions+of+%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0A%60%60%60&title=PANIC%3A+index+out+of+bounds%3A+the+len+is+1+but+the+index+is+1&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at yw.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:92:645)
    at /usr/src/app/node_modules/@prisma/client/runtime/index.js:129:3186
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async $w.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:211:3203)
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /usr/src/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
