### ISSUE TITLE
PANIC: Started http server on http+unix:///tmp/prisma-4853a1cebce032c1dde71620.sock

### ISSUE THREAD

**Issue by mohammadhmn** [prisma/prisma-client-js#942]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v10.23.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.12.1             |

# Description
```
signalCode: null | exitCode: 255 | killed: true
SocketError: closed
    at Socket.onSocketClose (/home/username/projects/server/node_modules/@prisma/client/runtime/index.js:25659:33)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
Exit code: 255
Started http server on http+unix:///tmp/prisma-4853a1cebce032c1dde71620.sock
```

## Logs
```
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  prisma-client { clientVersion: '2.12.1' }  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/username/projects/server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by timsuchanek** [comment]
Ping @mohammadhmn
