### ISSUE TITLE
PANIC: 1

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma-client-js#957]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.5.0            | 
| OS              | darwin             |
| Prisma Client   | 2.13.1             |

## Logs
```
prisma-client { clientVersion: '2.13.1' }
plusX Execution permissions of /Users/pieter/Invisible/invisible/node_modules/.prisma/client/query-engine-darwin are fine
plusX Execution permissions of /Users/pieter/Invisible/invisible/node_modules/.prisma/client/query-engine-darwin are fine
```

**Comment by cyrus-za** [comment]
Some more info after adding `DEBUG=prisma-client,engine`

```sh
[=== ] info  - Generating static pages (4/19)2020-12-30T11:45:44.629Z engine stdout {
  timestamp: 'Dec 30 13:45:44.628',
  level: 'ERROR',
  fields: {
    message: 'PANIC',
    reason: '1',
    file: 'query-engine/core/src/interpreter/query_interpreters/nested_read.rs',
    line: 78,
    column: 56
  },
  target: 'query_engine'
}
2020-12-30T11:45:44.630Z engine TypeError: this.currentRequestPromise.cancel is not a function
    at NodeEngine.handlePanic (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:26799:36)
    at EventEmitter.<anonymous> (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:26733:18)
    at EventEmitter.emit (events.js:200:13)
    at LineStream.<anonymous> (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:27039:33)
    at LineStream.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at LineStream.Readable.push (_stream_readable.js:210:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:24043:19) {"timestamp":"Dec 30 13:45:44.628","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}
2020-12-30T11:45:44.632Z engine {
  error: SocketError: closed
      at Socket.onSocketClose (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:25189:33)
      at Socket.emit (events.js:200:13)
      at Pipe.<anonymous> (net.js:588:12) {
    name: 'SocketError',
    code: 'UND_ERR_SOCKET'
  }
}
2020-12-30T11:45:44.635Z prisma-client Error: PANIC: 1

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v12.5.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.13.1+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma-client+%7B+clientVersion%3A+%272.13.1%27+%7D%0Aprisma-client+Prisma+Client+call%3A%0Aprisma-client+prisma.role.findMany%28%7B%0A++include%3A+%7B%0A++++users%3A+%7B%0A++++++select%3A+%7B%0A++++++++id%3A+true%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D%29%0Aprisma-client+Generated+request%3A%0Aprisma-client+query+%7B%0A++findManyRole+%7B%0A++++id%0A++++name%0A++++users+%7B%0A++++++id%0A++++%7D%0A++%7D%0A%7D%0A%0AplusX+Execution+permissions+of+%2FUsers%2Fpieter%2FInvisible%2Finvisible%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine%0AplusX+Execution+permissions+of+%2FUsers%2Fpieter%2FInvisible%2Finvisible%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine%0A%60%60%60&title=PANIC%3A+1&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at NodeEngine.handleRequestError (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:26642:21)
    at /Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:27295:36
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at async PrismaClientFetcher.request (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:78094:24)

Error occurred prerendering page "/permissions". Read more: https://err.sh/next.js/prerender-error
Error: 
Invalid `prisma.role.findMany()` invocation:


  PANIC: 1

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v12.5.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.13.1+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma-client+%7B+clientVersion%3A+%272.13.1%27+%7D%0Aprisma-client+Prisma+Client+call%3A%0Aprisma-client+prisma.role.findMany%28%7B%0A++include%3A+%7B%0A++++users%3A+%7B%0A++++++select%3A+%7B%0A++++++++id%3A+true%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D%29%0Aprisma-client+Generated+request%3A%0Aprisma-client+query+%7B%0A++findManyRole+%7B%0A++++id%0A++++name%0A++++users+%7B%0A++++++id%0A++++%7D%0A++%7D%0A%7D%0A%0AplusX+Execution+permissions+of+%2FUsers%2Fpieter%2FInvisible%2Finvisible%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine%0AplusX+Execution+permissions+of+%2FUsers%2Fpieter%2FInvisible%2Finvisible%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine%0A%60%60%60&title=PANIC%3A+1&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at PrismaClientFetcher.request (/Users/pieter/Invisible/invisible/node_modules/@prisma/client/runtime/index.js:78129:15)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
2020-12-30T11:45:44.642Z engine Restart attempt 1. Waiting for backoff
2020-12-30T11:45:44.642Z engine Restart attempt 1. Backoff done
2020-12-30T11:45:44.643Z engine { cwd: '/Users/pieter/Invisible/invisible/libs/flow-data/prisma' }
2020-12-30T11:45:44.643Z engine Search for Query Engine in /Users/pieter/Invisible/invisible/node_modules/.prisma/client
2020-12-30T11:45:44.644Z engine {
  flags: [
    '--enable-raw-queries',
    '--unix-path',
    '/tmp/prisma-28b1c18fec34781f741ff8e6.sock'
  ]
}
2020-12-30T11:45:44.653Z prisma-client Prisma Client call:
2020-12-30T11:45:44.653Z prisma-client prisma.role.findMany(undefined)
2020-12-30T11:45:44.653Z prisma-client Generated request:
2020-12-30T11:45:44.653Z prisma-client query {
  findManyRole {
    id
    name
  }
}
```

**Comment by cyrus-za** [comment]
Also, I am experiencing this locally, inside github actions and in vercel. Everything worked fine and then suddenly it changes

**Comment by Jolg42** [comment]
Was it working with the same version `2.13.1` or did it break after an upgrade?

**Comment by cyrus-za** [comment]
Worked with 2.13.1

I've realized that the issue is only on the staging DB and not on my local one. It only failed on a particular next page which called 
```ts
prisma.role.findMany({
    include: { users: { select: { id: true } } },
  });
```

Removing the include fixed the issue, so I looked into the auto-created `_RoleToUser` table which had 3 rows

```
A | B 
1 | 1
2 | 2
3 | 2
```

(user 1 had admin role and user 2 had the other 2 roles)

I deleted those 3 entries and added the include back and it worked. I then opened prisma studio, reassigned the roles and it worked again. So there must've been some hidden entries or something that I could not see in prisma studio or via psql that had that table messed up. 

I did run some manual migrations a day or so before this occurred, so many the `prisma migrate deploy` broke staging and I only realized it by the time the data and queries aligned to produce the error. 

What would be nice is if prisma could give some more concrete errors. There's no underlying sql error being exposed here. It was not even clear that the issue was on the join table or calling `include`. All I knew was that a particular nextjs page was failing in SSG and I had to go from there.

**Comment by pantharshit00** [comment]
Looks like a duplicate of https://github.com/prisma/prisma-client-js/issues/955

I will wait for that to be fixed here.
